// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

// Polish catalog. Entries not yet translated stay synchronized with the
// English source and are replaced in subsequent localization passes.
extension Strings {
    static let pl = Strings(
        statusIdleTooltip: "Vorssaint: normalny tryb uśpienia",
        statusActiveUntil: "Vorssaint: nie usypiaj do",
        statusActiveIndefinite: "Vorssaint: nie usypiaj bezterminowo",
        menuEnableAwake: "Włącz nieusypianie",
        menuDisableAwake: "Wyłącz nieusypianie",
        menuActivateFor: "Włącz na…",
        menuSettings: "Ustawienia…",
        menuAbout: "O Vorssaint",
        menuQuit: "Zakończ Vorssaint",
        menuHide: "Ukryj Vorssaint",
        menuHideOthers: "Ukryj pozostałe",
        menuShowAll: "Pokaż wszystkie",
        menuEdit: "Edycja",
        menuUndo: "Cofnij",
        menuRedo: "Ponów",
        actionClear: "Wyczyść",
        actionRemove: "Usuń",
        actionBack: "Wstecz",
        actionSearch: "Szukaj",
        actionMute: "Wycisz",
        actionUnmute: "Włącz dźwięk",
        actionPlay: "Odtwórz",
        actionPause: "Wstrzymaj",
        menuCut: "Wytnij",
        menuCopy: "Kopiuj",
        menuPaste: "Wklej",
        menuSelectAll: "Zaznacz wszystko",
        menuWindow: "Okno",
        menuMinimize: "Minimalizuj",
        menuZoom: "Powiększ",
        menuClose: "Zamknij",
        minutes15: "15 minut",
        minutes30: "30 minut",
        hour1: "1 godzina",
        hours2: "2 godziny",
        hours4: "4 godziny",
        hours8: "8 godzin",
        indefinitely: "Bezterminowo",
        indefinite: "Bezterminowo",
        panelSettings: "Ustawienia",
        panelQuit: "Zakończ",
        panelHotkeyHint: "Skrót przełącza",
        keepAwakeTitle: "Nie usypiaj",
        keepAwakeEndsIn: "Kończy się za",
        keepAwakeUntilDisabled: "Aktywne do wyłączenia",
        keepAwakeNormalRules: "Mac korzysta z normalnych zasad zasilania",
        keepAwakeUntilLabel: "Do",
        keepAwakeUntilStart: "Uruchom",
        keepAwakeOptions: "Opcje",
        keepAwakeMouseJiggle: "Poruszaj lekko kursorem",
        keepAwakeMouseJiggleCaption: "Podczas sesji lekko porusza kursorem w wybranym odstępie.",
        keepAwakeMouseJiggleInterval: "Odstęp",
        keepAwakeActiveIconLabel: "Aktywna ikona",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kawa",
        keepAwakeActiveIconEye: "Oko",
        keepAwakeActiveIconMoon: "Księżyc",
        keepAwakeActiveIconLight: "Żarówka",
        keepAwakeIconTintLabel: "Kolor aktywnej ikony",
        keepAwakeIconTintOrange: "Pomarańczowy",
        keepAwakeIconTintGreen: "Zielony",
        keepAwakeIconTintBlue: "Niebieski",
        keepAwakeIconTintPurple: "Fioletowy",
        keepAwakeIconTintPink: "Różowy",
        keepAwakeIconTintNone: "Bez koloru",
        durationLabel: "Czas trwania",
        clamshellTitle: "Nie usypiaj przy zamkniętej pokrywie",
        clamshellOnCaption: "Uśpienie jest całkowicie wyłączone. Zwróć uwagę na zasilanie.",
        clamshellNeedsSession: "Będzie stosowane, gdy „Nie usypiaj” jest aktywne.",
        clamshellReady: "Gotowe. Włącza się i wyłącza bez hasła",
        clamshellNeedsPassword: "Poprosi raz o hasło administratora",
        systemSection: "System",
        temperatures: "Temperatury",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Bateria",
        usageSection: "Użycie sprzętu",
        memorySection: "Pamięć",
        memoryPressure: "Presja pamięci",
        memorySwapUsed: "Użycie pamięci wymiany",
        memoryCompressed: "Skompresowana",
        memoryCachedFiles: "Pliki w pamięci podręcznej",
        pressureNormal: "Normalna",
        pressureWarning: "Ostrzeżenie",
        pressureCritical: "Krytyczna",
        monitorUnavailable: "Czujniki są niedostępne na tym Macu",
        energyAppsTitle: "Znaczące użycie energii",
        energyAppsIdle: "Brak znaczącego użycia energii",
        notifySessionEndedTitle: "Sesja zakończona",
        notifySessionEndedBody: "Czas minął. Mac wróci do normalnego uśpienia.",
        notifyBatteryTitle: "Vorssaint wyłączony",
        notifyBatteryBody: "Niski poziom baterii. Przywrócono normalne uśpienie, aby chronić baterię.",
        adminPromptClamshellOn: "Vorssaint potrzebuje hasła, aby utrzymać Maca aktywnego przy zamkniętej pokrywie.",
        adminPromptClamshellOff: "Vorssaint potrzebuje hasła, aby ponownie włączyć normalne uśpienie Maca.",
        adminPromptRecover: "Vorssaint został zamknięty przy wyłączonym uśpieniu Maca. Wprowadź hasło, aby przywrócić normalne uśpienie.",
        adminPromptUpdate: "Vorssaint potrzebuje hasła, aby zainstalować aktualizację.",
        adminPromptSudoersInstall: "Vorssaint utworzy ograniczoną regułę (tylko pmset disablesleep), która pozwoli przełączać tryb przy zamkniętej pokrywie bez pytania o hasło. Hasło będzie potrzebne tylko teraz.",
        adminPromptSudoersRemove: "Vorssaint usunie regułę pozwalającą na tryb przy zamkniętej pokrywie bez hasła.",
        settingsTitle: "Ustawienia Vorssaint",
        tabGeneral: "Ogólne",
        tabEnergy: "Zasilanie",
        tabMouse: "Mysz i gładzik",
        tabSwitcher: "Przełącznik",
        tabAdvanced: "Zaawansowane",
        tabAbout: "O aplikacji",
        tabReleaseNotes: "Nowości",
        releaseNotesOnUpdateToggle: "Pokazuj nowości po aktualizacji",
        minimalWindowPreviews: "Minimalne podglądy okien",
        minimalWindowPreviewsCaption: "Ukrywa tytuły, przyciski i dekoracyjne szczegóły w podglądach Docka i przełącznika. Zaznaczenie pozostaje widoczne.",
        previewSizeLabel: "Rozmiar podglądu",
        previewSizeNormal: "Normalny",
        previewSizeLarge: "Duży",
        previewSizeXLarge: "Bardzo duży",
        settingsGroupFeatures: "Funkcje",
        advancedResetSection: "Uprawnienia",
        advancedResetDescription: "Usuwa wszystkie uprawnienia przyznane Vorssaint, element logowania i regułę zamkniętej pokrywy. Przydatne przed ponowną konfiguracją lub odinstalowaniem. Aplikacja pozostaje zainstalowana.",
        advancedClearButton: "Wyczyść wszystkie uprawnienia",
        advancedCleared: "Uprawnienia wyczyszczone.",
        advancedClearFailed: "Nie udało się usunąć części uprawnień lub reguły zamkniętej pokrywy. Spróbuj ponownie i zaakceptuj prośbę o hasło, jeśli się pojawi.",
        advancedClearConfirmTitle: "Wyczyścić wszystkie uprawnienia?",
        advancedClearConfirmBody: "Funkcje wymagające uprawnień przestaną działać, dopóki nie przyznasz ich ponownie. Ustawienia zostaną zachowane.",
        advancedUninstallSection: "Odinstalowanie",
        advancedUninstallDescription: "Wykonuje powyższe czynności, usuwa ustawienia i przenosi Vorssaint do Kosza bez pozostawiania śladów. Po zakończeniu aplikacja zostanie zamknięta.",
        advancedUninstallButton: "Całkowicie odinstaluj Vorssaint",
        advancedUninstallConfirmTitle: "Odinstalować Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint wyczyści uprawnienia, usunie ustawienia i przeniesie się do Kosza, a następnie zakończy działanie. Nie można cofnąć tego z poziomu aplikacji, ale aplikacja pozostanie w Koszu do jego opróżnienia.",
        advancedUninstallFailedTitle: "Odinstalowanie przerwane",
        advancedUninstallFailedBody: "Vorssaint nie mógł przywrócić ustawienia systemowego, które zmienił: uśpienia, prędkości wentylatorów lub akceleracji myszy. Nic nie zostało usunięte.",
        launchAtLogin: "Uruchamiaj przy logowaniu",
        languageLabel: "Język",
        menuBarSection: "Pasek menu",
        showCountdown: "Pokazuj pozostały czas obok ikony",
        globalHotkeySection: "Skrót globalny",
        hotkeyToggle: "Włącz skrót „Nie usypiaj”",
        hotkeyCaption: "Działa w każdej aplikacji, bez dodatkowych uprawnień.",
        sessionSection: "Sesja",
        defaultDurationLabel: "Domyślny czas trwania",
        keepAwakeAutoStart: "Nie usypiaj po uruchomieniu Vorssaint",
        keepAwakeAutoStartCaption: "Uruchamia sesję z domyślnym czasem trwania.",
        batteryProtectionSection: "Ochrona baterii",
        batteryDisableBelow: "Wyłącz, gdy bateria spadnie poniżej",
        batteryNever: "Nigdy",
        batteryProtectionCaption: "Chroni MacBooka przed rozładowaniem przez zapomnianą sesję.",
        clamshellSection: "Zamknięta pokrywa",
        configuring: "Konfigurowanie…",
        sudoersFailed: "Nie udało się włączyć trybu zamkniętej pokrywy. Spróbuj ponownie.",
        clamshellExplanation: "„Nie usypiaj przy zamkniętej pokrywie” całkowicie wyłącza uśpienie, gdy „Nie usypiaj” jest aktywne, i automatycznie przywraca je po zakończeniu sesji lub zamknięciu aplikacji. Najlepiej używać po podłączeniu zasilania.",
        scrollSection: "Przewijanie",
        invertMouseScroll: "Odwróć przewijanie myszy",
        invertMouseScrollCaption: "Odwraca kierunek kółka myszy.",
        scrollTrackpadNote: "Gładzik pozostaje bez zmian: zachowuje naturalne przewijanie macOS.",
        scrollActiveNow: "W tej chwili odwracane jest przewijanie myszy",
        mouseNavigationActiveNow: "Przyciski boczne są teraz aktywne",
        smoothScrollName: "Płynne przewijanie",
        smoothScrollCaption: "Zamienia każdy krok kółka myszy na krótkie, płynne przesunięcie. Gładzik nie jest zmieniany.",
        smoothScrollStepLabel: "Szybkość przewijania",
        mouseNavigationSection: "Nawigacja",
        mouseNavigationEnable: "Używaj przycisków bocznych do Wstecz i Dalej",
        mouseNavigationCaption: "Zamienia przyciski Wstecz i Dalej myszy na polecenia nawigacji w Finderze, przeglądarkach i zgodnych aplikacjach.",
        middleClickSection: "Środkowy przycisk",
        middleClickEnable: "Kliknięcie trzema palcami działa jak środkowy przycisk",
        middleClickEnableCaption: "Naciśnięcie gładzika trzema palcami działa jak kliknięcie kółkiem myszy: otwiera linki w nowej karcie, zamyka karty i wykonuje inne działania środkowego przycisku.",
        middleClickDragConflict: "W macOS włączone jest przeciąganie trzema palcami i używa tego samego gestu. Wyłącz je w Ustawieniach systemowych w Dostępność → Sterowanie wskaźnikiem → Opcje gładzika, a środkowe kliknięcie będzie działać.",
        middleClickTapPicker: "Lekkie stuknięcie również klika",
        middleClickTapOff: "Wyłączone",
        middleClickTapThreeFingers: "3 palce",
        middleClickTapFourFingers: "4 palce",
        middleClickTapCaption: "Lekkie stuknięcie tyloma palcami, bez naciskania, również wykonuje środkowe kliknięcie. Przesuwanie nigdy się nie liczy. Jeśli stuknięcie trzema palcami w macOS jest przypisane do Wyszukiwania, wyłącz je, aby oba gesty nie uruchamiały się jednocześnie.",
        quickToolsTab: "Panel szybkich narzędzi",
        quickToolShortcutToggle: "Skrót globalny",
        ocrName: "Kopiuj tekst z ekranu",
        ocrCaption: "Zaznacz obszar ekranu, a rozpoznany tekst zostanie skopiowany i będzie gotowy do wklejenia.",
        ocrCopied: "Tekst skopiowany",
        ocrNoText: "Nie znaleziono tekstu",
        colorPickerName: "Próbnik kolorów",
        colorPickerCaption: "Pobierz kolor dowolnego piksela ekranu i skopiuj go w wybranym formacie.",
        colorPickerFormatLabel: "Format kopiowania",
        colorPickerBareHexToggle: "Kopiuj bez prefiksu #",
        colorPickerPickNow: "Pobierz kolor",
        micMuteName: "Wycisz mikrofon",
        micUnmuteName: "Włącz mikrofon",
        micMuteCaption: "Jednym kliknięciem lub skrótem wycisza mikrofon Maca we wszystkich aplikacjach.",
        micMutedHUD: "Mikrofon wyciszony",
        micUnmutedHUD: "Mikrofon włączony",
        micMutePartialHUD: "Nie udało się wyciszyć części mikrofonów",
        micUnmutePartialHUD: "Część mikrofonów nadal jest wyciszona",
        micMuteMenuBarToggle: "Pokazuj na pasku menu podczas wyciszenia",
        micMuteMenuBarCaption: "Czerwony przekreślony mikrofon pojawia się obok ikony aplikacji na pasku menu.",
        pastePlainName: "Wklej jako zwykły tekst",
        pastePlainCaption: "Wkleja skopiowaną treść bez kolorów, czcionek i formatowania. Oryginał pozostaje w schowku.",
        launcherName: "Panel szybkich narzędzi",
        launcherCaption: "Pływający panel z ulubionymi narzędziami, otwierany skrótem z dowolnego miejsca.",
        launcherOpenNow: "Otwórz panel szybkich narzędzi",
        launcherEditHint: "Użyj przycisku konfiguracji, aby wybierać, ukrywać i przeciągać narzędzia.",
        launcherEmptyState: "Wszystkie narzędzia są ukryte. Użyj przycisku konfiguracji, aby je przywrócić.",
        launcherAddSection: "Dodaj ponownie",
        launcherKeysHint: "Strzałki nawigują, Enter otwiera, 1–9 otwierają bezpośrednio",
        switcherSection: "Przełącznik aplikacji",
        switcherEnable: "Używaj przełącznika Vorssaint",
        switcherEnableCaption: "Przełączaj aplikacje i okna, także zminimalizowane oraz wiele okien tej samej aplikacji.",
        switcherUsageHint: "Przytrzymaj skrót, aby nawigować; zwolnij, aby aktywować okno. Shift lub ← cofa; W zamyka okno; Q kończy aplikację; Esc anuluje.",
        switcherNoWindows: "Brak otwartych okien",
        switcherIconRowMode: "Pokaż %@ z dużymi ikonami",
        switcherIconRowModeCaption: "Pokazuje jedną ikonę na aplikację oraz podglądy jej okien powyżej.",
        switcherSimpleModeCaption: "Pokazuje ikony aplikacji i tytuły okien bez podglądów i przechwytywania ekranu przez przełącznik.",
        switcherShortcutHintApps: "Aplikacje",
        switcherShortcutHintWindows: "Okna",
        switcherWindowShortcutCaption: "Otwiera przełącznik okien aplikacji znajdującej się na pierwszym planie. Gdy przełącznik aplikacji jest otwarty, przełącza między oknami wybranej aplikacji.",
        switcherTakeOverSystemShortcuts: "Zastąp ⌘Tab i ⌘` macOS",
        switcherTakeOverSystemShortcutsCaption: "Wyłącza odpowiednie skróty aplikacji i okien macOS tylko wtedy, gdy przełącznik Vorssaint jest aktywny. Wszystkie uruchomione aplikacje pozostają dostępne.",
        switcherAppearanceDelay: "Opóźnienie wyświetlania",
        switcherAppearanceDelayCaption: "Jak długo trzeba przytrzymać skrót, zanim pojawi się przełącznik.",
        switcherMergeTabs: "Pokazuj jeden wpis na aplikację",
        switcherMergeTabsCaption: "Łączy wszystkie okna aplikacji w jeden wpis zamiast osobnego wpisu dla każdego okna.",
        switcherWindowlessApps: "Aplikacje bez otwartego okna",
        switcherWindowlessAppsCaption: "Wybiera, które uruchomione aplikacje bez żadnego okna mają być widoczne w przełączniku.",
        switcherWindowlessAppsOff: "Nie pokazuj",
        switcherWindowlessAppsFinder: "Tylko Finder",
        switcherWindowlessAppsAll: "Wszystkie aplikacje",
        switcherNoOpenWindow: "Brak otwartego okna",
        switcherOtherDesktop: "Inne biurko",
        dockPreviewName: "Podgląd Docka",
        dockPreviewEnable: "Podglądaj okna z Docka",
        dockPreviewEnableCaption: "Najedź na otwartą aplikację w Docku, aby zobaczyć jej okna, a następnie kliknij wybrane.",
        dockPreviewCurrentSpaceOnlyCaption: "Po wyłączeniu pokazuje okna ze wszystkich biurek. Wybór okna z innego biurka przenosi na nie.",
        dockPreviewBackgroundOpacity: "Tło panelu",
        dockPreviewBackgroundOpacityCaption: "Zmniejsz krycie, aby zobaczyć więcej tego, co znajduje się za panelem.",
        dockPreviewOpenDelay: "Opóźnienie otwierania",
        dockPreviewOpenDelayCaption: "Jak długo wskaźnik musi pozostawać nad ikoną, zanim otworzy się jej panel.",
        dockPreviewQuitAppOnClose: "Zakończ aplikację przyciskiem ×",
        dockPreviewQuitAppOnCloseCaption: "W Podglądzie Docka przycisk × kończy całą aplikację zamiast zamykać tylko to okno.",
        dockPreviewKeepDockVisible: "Zachowaj Dock widoczny (eksperymentalne)",
        dockPreviewKeepDockVisibleCaption: "Wstrzymuje automatyczne ukrywanie Docka podczas otwartego podglądu i przywraca je po wyjściu. Może zmieniać rozmiar okien. Jeśli aplikacja zostanie przerwana, uruchom ją ponownie, aby przywrócić Dock.",
        dockPreviewOrderByCreation: "Sortuj okna według czasu utworzenia",
        dockPreviewOrderByCreationCaption: "Pokazuj starsze okna przed tymi używanymi ostatnio.",
        dockClickMinimize: "Kliknij ikonę Docka, aby zminimalizować",
        dockClickMinimizeCaption: "Okna aktywnej aplikacji są minimalizowane po kliknięciu jej ikony w Docku. Kliknij ponownie, aby je przywrócić.",
        dockClickCycleWindows: "Kliknij ikonę Docka, aby przełączać okna",
        dockClickCycleWindowsCaption: "Kliknij ikonę aktywnej aplikacji w Docku, aby przełączać jej okna jak przy ⌘`.",
        dockPreviewActiveNow: "Aktywne w Docku",
        dockPreviewDockUnavailable: "Nie udało się odczytać elementów Docka.",
        dockPreviewAutohideBeta: "Beta. Mogą wystąpić błędy.",
        dockPreviewOpenWindow: "Otwórz okno",
        dockPreviewCloseWindow: "Zamknij okno",
        dockPreviewMinimizeWindow: "Minimalizuj okno",
        dockPreviewRestoreWindow: "Przywróć okno",
        dockPreviewPinPanel: "Przypnij podgląd",
        dockPreviewUnpinPanel: "Odepnij podgląd",
        dockPreviewPinned: "Przypięte",
        dockPreviewClosePanel: "Zamknij podgląd",
        dockPreviewPreviousWindow: "Poprzednie okno",
        dockPreviewNextWindow: "Następne okno",
        cutPasteName: "Wytnij i wklej",
        cutPasteEnable: "Wycinaj i wklejaj pliki w Finderze",
        cutPasteEnableCaption: "Użyj ⌘X, aby wycinać, i ⌘V, aby przenosić pliki i foldery w Finderze.",
        cutPasteShowHUD: "Pokaż pływający panel",
        cutPasteShowHUDCaption: "Pokazuje wskaźnik z wyciętymi plikami, gdy Finder jest aktywny.",
        cutPasteHowTitle: "Jak używać",
        cutPasteStep1: "Zaznacz elementy w Finderze i naciśnij ⌘X, aby je wyciąć.",
        cutPasteStep2: "Otwórz folder docelowy i naciśnij ⌘V, aby je tam przenieść.",
        cutPasteTextNote: "W polach tekstowych, np. podczas zmiany nazwy, ⌘X i ⌘V nadal działają normalnie.",
        cutPasteActiveNow: "Gotowe do wycinania w Finderze",
        cutPasteAutomationNote: "Przy pierwszym użyciu macOS poprosi o zgodę na sterowanie Finderem.",
        cutReadyTitle: "Wycięto",
        cutReadyHint: "w folderze docelowym do przeniesienia",
        cutCancel: "Anuluj wycinanie",
        cutDoneTitle: "Przeniesiono!",
        cutMovedSingular: "1 element przeniesiony",
        cutMovedPluralFormat: "Przeniesiono %d elementów",
        cutSomeFailed: "Nie udało się przenieść części elementów",
        cutMovingTitle: "Przenoszenie…",
        cutMovingCountFormat: "%d z %d",
        autoQuitName: "Zakończ po zamknięciu",
        autoQuitEnable: "Zakończ aplikację po zamknięciu ostatniego okna",
        autoQuitEnableCaption: "Zamknięcie ostatniego okna aplikacji kończy również jej działanie.",
        autoQuitActiveNow: "Aktywne",
        autoQuitHowTitle: "Jak to działa",
        autoQuitStep1: "Zamknij ostatnie okno aplikacji (⌘W lub czerwonym przyciskiem).",
        autoQuitStep2: "Aplikacja zakończy działanie sama. Dialogi „Zachować zmiany?” nadal będą się pojawiać.",
        autoQuitPredictableNote: "Aplikacje, które zwykle działają bez okna, nigdy nie są kończone.",
        autoQuitExceptionsTitle: "Wyjątki",
        autoQuitExceptionsCaption: "Aplikacje z tej listy pozostają otwarte nawet bez okien.",
        autoQuitExceptionsEmpty: "Brak wyjątków",
        autoQuitAddApp: "Dodaj aplikację…",
        uninstallerName: "Odinstalator",
        uninstallerEnableCaption: "Usuwa aplikację razem z pozostawionymi przez nią pamięciami podręcznymi, ustawieniami, logami i resztkami.",
        uninstallerStep1: "Przeciągnij aplikację do Ustawień albo wybierz ją z listy.",
        uninstallerStep2: "Sprawdź znalezione pliki i zajmowane przez nie miejsce.",
        uninstallerStep3: "Przenieś wybrane elementy do Kosza. Nic nie jest trwale usuwane.",
        uninstallerMenuItem: "Odinstaluj aplikację…",
        uninstallerDropTitle: "Przeciągnij tutaj aplikację",
        uninstallerDropSubtitle: "albo wybierz ją do skanowania",
        uninstallerChoose: "Wybierz aplikację…",
        uninstallerPickerTitle: "Wybierz aplikację",
        uninstallerPickerSearch: "Szukaj aplikacji",
        uninstallerPickerEmpty: "Nie znaleziono aplikacji",
        uninstallerEmptyNote: "Nic nie zostanie usunięte bez Twojego potwierdzenia.",
        uninstallerFDANote: "Przyznaj Pełny dostęp do dysku, aby wykonać dokładniejsze skanowanie.",
        uninstallerFDAGrant: "Przyznaj dostęp…",
        uninstallerFDAHint: "Włącz Vorssaint na liście. Jeśli go tam nie ma, kliknij + i wybierz Vorssaint z folderu Programy. Dostęp zacznie działać po ponownym otwarciu aplikacji.",
        uninstallerFDARelaunch: "Uruchom ponownie teraz",
        uninstallerScanning: "Skanowanie plików…",
        uninstallerRemoving: "Przenoszenie do Kosza…",
        uninstallerFoundTitle: "znaleziono",
        uninstallerSelectedFormat: "Zaznaczono %d z %d",
        uninstallerRemove: "Przenieś do Kosza",
        uninstallerCancel: "Anuluj",
        uninstallerDoneTitle: "Gotowe!",
        uninstallerFreedFormat: "Odzyskano %@",
        uninstallerSomeFailed: "Nie udało się przenieść części elementów do Kosza.",
        uninstallerFailedNeedsFDA: "Dane aplikacji w piaskownicy można przenieść tylko przy pełnym dostępie do dysku. Hasło administratora go nie zastępuje.",
        uninstallerFailedMoreFormat: "i jeszcze %d",
        uninstallerAnother: "Odinstaluj kolejną",
        uninstallerCatApp: "Aplikacja",
        uninstallerCatSupport: "Wsparcie",
        uninstallerCatCaches: "Pamięć podręczna",
        uninstallerCatPreferences: "Ustawienia",
        uninstallerCatContainers: "Kontenery",
        uninstallerCatLogs: "Logi",
        uninstallerCatState: "Zapisany stan",
        uninstallerCatOther: "Inne",
        uninstallerCommandBarBrowseTitle: "Odinstaluj aplikację",
        uninstallerCommandBarToggle: "Pokaż w pasku poleceń",
        uninstallerCommandBarCaption: "Wybieraj i odinstalowuj aplikacje w pasku poleceń.",
        uninstallerCommandBarFinderTitle: "Odinstaluj aplikację zaznaczoną w Finderze",
        uninstallerSelectionUnavailable: "Wybierz aplikację, którą można usunąć w Finderze, albo wybierz inną z listy.",
        urlCleanerName: "Wyczyść adres URL",
        urlCleanerEnable: "Czyść adresy URL przy kopiowaniu",
        urlCleanerEnableCaption: "Usuwa parametry śledzące z linku, gdy tylko trafi on do schowka.",
        urlCleanerActiveNow: "Aktywne",
        urlCleanerManualTitle: "Wyczyść teraz",
        urlCleanerInputPlaceholder: "Wklej adres URL",
        urlCleanerOutputPlaceholder: "Oczyszczony adres URL pojawi się tutaj",
        urlCleanerCleanButton: "Wyczyść",
        urlCleanerPasteButton: "Wklej",
        urlCleanerCopyButton: "Kopiuj",
        urlCleanerClearButton: "Wyczyść pole",
        urlCleanerNoURL: "Wklej prawidłowy adres URL.",
        urlCleanerNoChange: "Nie ma nic do wyczyszczenia.",
        urlCleanerCleaned: "Adres URL wyczyszczony.",
        urlCleanerCopied: "Skopiowano.",
        urlCleanerLocalNote: "Lokalnie. Bez sieci.",
        homebrewName: "Homebrew",
        homebrewEnableCaption: "Szukaj, instaluj i usuwaj formuły oraz caski.",
        homebrewMissingTitle: "Nie znaleziono Homebrew",
        homebrewMissingBody: "Vorssaint może otworzyć Terminal z oficjalnym instalatorem Homebrew. Terminal pokaże kroki i poprosi o hasło, jeśli będzie potrzebne.",
        homebrewInstallHomebrew: "Zainstaluj Homebrew",
        homebrewInstallHomebrewCaption: "Po zakończeniu pracy Terminala wróć tutaj i kliknij Odśwież.",
        homebrewInstallHomebrewOpened: "Instalator został otwarty w Terminalu.",
        homebrewShellSetupTitle: "Dokończ konfigurację Terminala",
        homebrewShellSetupBody: "Homebrew jest zainstalowany, ale Terminal może jeszcze nie znać polecenia brew. Vorssaint może otworzyć Terminal z poleceniem konfiguracji.",
        homebrewShellSetupButton: "Skonfiguruj Terminal",
        homebrewShellSetupOpened: "Polecenie otwarto w Terminalu. Wróć tutaj i kliknij Odśwież.",
        homebrewRefresh: "Odśwież",
        homebrewCheckPackages: "Sprawdź pakiety",
        homebrewTrustTitle: "Tap nie jest jeszcze zaufany",
        homebrewTrustCaption: "Homebrew prosi teraz o potwierdzenie przed użyciem zewnętrznych tapów. Zaufaj %@, aby kontynuować.",
        homebrewTrustButton: "Zaufaj i kontynuuj",
        homebrewSearchPlaceholder: "Szukaj pakietów",
        homebrewKeyboardHint: "Spacja lub Return zamyka panel macOS. Użyj przycisku wyszukiwania.",
        homebrewSearchButton: "Szukaj",
        homebrewSearchResults: "Wyniki",
        homebrewInstalled: "Zainstalowane",
        homebrewAll: "Wszystkie",
        homebrewFormulas: "Formuły",
        homebrewCasks: "Caski",
        homebrewNoPackages: "Nie znaleziono pakietów",
        homebrewDependencies: "Zależności",
        homebrewNoSelection: "Wybierz zainstalowany pakiet albo wyszukaj nowy.",
        homebrewDetailsTitle: "Szczegóły pakietu",
        homebrewInstall: "Zainstaluj",
        homebrewUninstall: "Odinstaluj",
        homebrewUpgrade: "Aktualizuj",
        homebrewUpgradeAll: "Aktualizuj wszystkie",
        homebrewUpdateHomebrew: "Aktualizuj Homebrew",
        homebrewAllPackages: "pakietów",
        homebrewOpenTerminal: "Otwórz Terminal",
        homebrewCancelOperation: "Anuluj",
        homebrewClearLog: "Wyczyść dziennik",
        homebrewLogTitle: "Dziennik",
        homebrewVersion: "Wersja",
        homebrewDescription: "Typ",
        homebrewHomepage: "Otwórz stronę",
        homebrewPopularity: "Popularność",
        homebrewPopularityFormat: "%@ instalacji w ciągu %@ dni",
        homebrewInstalledBadge: "Zainstalowane",
        homebrewNotInstalledBadge: "Niezainstalowane",
        homebrewUpdates: "Aktualizacje",
        homebrewUpdateAvailableBadge: "Dostępna aktualizacja",
        homebrewLatestVersion: "Najnowsza",
        homebrewConfirmInstallTitle: "Zainstalować przez Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew pobierze i zainstaluje %@. Możliwe, że zostaną zainstalowane również zależności.",
        homebrewConfirmUninstallTitle: "Odinstalować przez Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew odinstaluje %@. Pliki konfiguracyjne mogą pozostać w systemie.",
        homebrewConfirmUpgradeTitle: "Zaktualizować przez Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew pobierze i zastosuje najnowszą wersję %@. Możliwe, że zostaną również zaktualizowane zależności.",
        homebrewConfirmUpgradeAllTitle: "Update all with Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew will download and apply the latest versions for packages with updates available. Dependencies may also be updated.",
        homebrewConfirmUpdateHomebrewTitle: "Update Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew will fetch the latest information and then reload your packages.",
        homebrewTerminalFallback: "This operation needs Terminal to ask for the administrator password. Vorssaint does not capture passwords.",
        homebrewLoading: "Loading…",
        homebrewSearchEmpty: "No results",
        homebrewOperationInstallFormat: "Installing %@",
        homebrewOperationUninstallFormat: "Uninstalling %@",
        homebrewOperationUpgradeFormat: "Updating %@",
        homebrewOperationUpgradeAll: "Updating packages",
        homebrewOperationUpdateHomebrew: "Updating Homebrew",
        homebrewOperationInstalledFormat: "%@ installed.",
        homebrewOperationUninstalledFormat: "%@ uninstalled.",
        homebrewOperationUpgradedFormat: "%@ updated.",
        homebrewOperationUpgradedAll: "Packages updated.",
        homebrewOperationUpdatedHomebrew: "Homebrew updated.",
        homebrewOperationFailedFormat: "Could not finish %@.",
        homebrewOperationCancelled: "Operation cancelled.",
        homebrewOperationPreparing: "Preparing…",
        homebrewOperationDownloading: "Downloading files…",
        homebrewOperationInstalling: "Installing files…",
        homebrewOperationUninstalling: "Removing files…",
        homebrewOperationUpgrading: "Updating files…",
        homebrewOperationFinalizing: "Finishing…",
        homebrewOperationRefreshing: "Refreshing list…",
        homebrewOperationTerminal: "Continue in Terminal.",
        homebrewOperationElapsedFormat: "%@ elapsed",
        homebrewOperationShowDetails: "Show details",
        homebrewOperationHideDetails: "Hide details",
        homebrewOperationTechnicalLog: "Technical details",
        homebrewOperationProgressUnknown: "Homebrew has not reported a percentage yet.",
        mediaName: "Media",
        mediaEnableCaption: "Compress videos, convert and process images, make GIFs and extract text locally.",
        mediaLocalNote: "Local. No network.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Image",
        mediaToolText: "Text",
        mediaSelectFile: "Choose file",
        mediaDropHint: "Drop a file here or click to choose one.",
        mediaOutput: "Output",
        mediaOutputAutomatic: "Automatic",
        mediaChooseOutput: "Destination",
        mediaStartVideo: "Compress video",
        mediaStartGIF: "Make GIF",
        mediaStartImage: "Process image",
        mediaStartConvertPDF: "Convert to PDF",
        mediaStartText: "Extract text",
        mediaCancel: "Cancel",
        mediaStartTime: "Start",
        mediaEndTime: "End",
        mediaQuality: "Compression",
        mediaCompressionLow: "Low",
        mediaCompressionMedium: "Medium",
        mediaCompressionHigh: "High",
        mediaCompressionLowDescription: "High quality, large file size",
        mediaCompressionMediumDescription: "Balanced quality and file size",
        mediaCompressionHighDescription: "Low quality, small file size",
        mediaMaxSize: "Size",
        mediaSizingResolution: "Resolution",
        mediaSizingFileSize: "File size",
        mediaTargetSize: "Target size",
        mediaTargetSizeHint: "Resolution adapts to stay under the limit.",
        mediaErrorTargetTooSmall: "Target size too small for this clip. Trim it or raise the limit.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Width",
        mediaFPS: "FPS",
        mediaKeepAudio: "Keep audio",
        mediaCodec: "Codec",
        mediaFormat: "Format",
        mediaStripMetadata: "Remove metadata",
        mediaLoopGIF: "Loop GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Accurate",
        mediaOCRFast: "Fast",
        mediaLanguageCorrection: "Language correction",
        mediaTextOutputNote: "Extracted text can be copied and saved as TXT.",
        mediaRunning: "Processing",
        mediaCompleted: "Done",
        mediaCancelled: "Cancelled.",
        mediaOpenInFinder: "Show",
        mediaCopyText: "Copy text",
        mediaRunAgain: "Run again",
        mediaEmptyText: "No text found.",
        mediaResultSavedFormat: "Saved as %@",
        mediaResultSizeFormat: "%@ to %@",
        mediaResultGrewCaption: "The converted file came out larger than the original.",
        mediaErrorNoFile: "Choose a file first.",
        mediaErrorNoVideo: "This file has no video track.",
        mediaErrorSameOutput: "Choose a destination different from the original file.",
        mediaErrorUnsupported: "Format not supported by macOS.",
        shelfName: "Shelf",
        shelfEnable: "Temporary area for dragging files",
        shelfEnableCaption: "A floating spot to gather files, images and text, then drag them anywhere later.",
        shelfHowTitle: "How to use",
        shelfStep1: "Open it with the shortcut, or by shaking the mouse during a drag.",
        shelfStep2: "Drop files, images, links or text onto it to hold them.",
        shelfStep3: "Drag each item back out to any app when you need it.",
        shelfShakeToggle: "Open by shaking the mouse while dragging",
        shelfShakeCaption: "Shake the pointer quickly while holding an item to summon it near the cursor.",
        shelfDropZoneToggle: "Keep dragged files in the menu bar",
        shelfDropZoneCaption: "While you drag a file, the shelf appears below the menu bar icon. Whatever you drop is kept right there, in a button you shrink and open with a click that goes away once the shelf is empty.",
        shelfDropZoneLabel: "Drop here",
        shelfCollapse: "Collapse",
        shelfBehaviorTitle: "After use",
        shelfCloseAfterDrop: "Close after dropping into another app",
        shelfCloseAfterDropCaption: "Closes the shelf when the destination accepts the items. The pin in the panel keeps it open.",
        shelfRemoveAfterDrop: "Remove items after dropping",
        shelfRemoveAfterDropCaption: "Items accepted by another app leave the shelf. Turn this off to keep a copy there.",
        shelfExclusionsTitle: "Automatic exceptions",
        shelfExclusionsEmpty: "No apps added.",
        shelfExclusionsCaption: "Shake and the menu bar drop zone stay off for drags started in these apps. The shortcut and Open now still work.",
        shelfPin: "Keep open",
        shelfUnpin: "Allow closing after use",
        extraBrightnessName: "Extra brightness",
        extraBrightnessCaption: "Uses the display’s HDR headroom to go past the maximum brightness. Uses more battery and the Mac can run warm.",
        extraBrightnessLevelLabel: "Intensity",
        extraBrightnessUnsupported: "Available only on XDR displays, such as the ones on the 14 and 16 inch MacBook Pro.",
        shelfHotkeyLabel: "Shortcut",
        shelfOpenNow: "Open now",
        shelfNoPermission: "Requires no permissions.",
        shelfMenuItem: "Open shelf",
        shelfTitle: "Shelf",
        shelfEmpty: "Drag items here",
        shelfClearAll: "Clear all",
        shelfRemoveSelected: "Remove selected",
        shelfSelectedFormat: "%d selected",
        shelfHint: "Click to select. Drag out to use or right-click for more actions.",
        shelfItemImage: "Image",
        shelfTooltipItemsFormat: "%d items",
        shelfTooltipItemsFew: "%d items",
        shelfTooltipImageSingular: "%d image",
        shelfTooltipImageFew: "%d images",
        shelfTooltipImagePlural: "%d images",
        shelfTooltipFileSingular: "%d file",
        shelfTooltipFileFew: "%d files",
        shelfTooltipFilePlural: "%d files",
        shelfTooltipNoteSingular: "%d note",
        shelfTooltipNoteFew: "%d notes",
        shelfTooltipNotePlural: "%d notes",
        shelfTooltipLinkSingular: "%d link",
        shelfTooltipLinkFew: "%d links",
        shelfTooltipLinkPlural: "%d links",
        shelfActionOpen: "Open",
        shelfActionOpenWith: "Open With",
        shelfActionShare: "Share",
        breakdownMeasuring: "Measuring…",
        mixerSection: "Volume mixer",
        mixerEmpty: "Apps that use audio show up here",
        mixerUnavailable: "Available on macOS 14.4 and later",
        mixerPermissionBody: "To adjust per-app volume, allow “Screen & System Audio Recording” in System Settings. Audio is never recorded.",
        mixerResetTooltip: "Reset to 100%",
        mixerOutputDefault: "Default",
        mixerOutputCurrent: "current",
        mixerOutputUnavailable: "Output unavailable",
        mixerOutputFallback: "Using default until this device returns.",
        mixerBypassedCaption: "This app manages its own audio.",
        mixerOutputTooltip: "Choose output",
        mixerSystemOutputTitle: "Output",
        mixerSystemOutputNoDevices: "No outputs found",
        mixerSystemOutputTooltip: "Choose system output",
        mixerSystemOutputErrorFormat: "Could not switch: %@",
        mixerLowerOnHeadphonesDisconnect: "Lower volume when headphones disconnect",
        mixerLowerOnHeadphonesDisconnectCaption: "Adjusts output when wired or Bluetooth headphones disconnect.",
        mixerHeadphonesDisconnectVolume: "Volume after disconnect",
        preciseVolumeRollerEnable: "Use finer volume steps",
        preciseVolumeRollerCaption: "Turns volume wheels and keys into smaller system volume steps.",
        preciseVolumeRollerTapFailed: "Could not listen for volume keys.",
        soundOutputSwitcherTitle: "Output switcher",
        soundOutputSwitcherEnable: "Switch outputs with shortcut",
        soundOutputSwitcherCaption: "Choose outputs and use the shortcut to move to the next available one.",
        soundOutputSwitcherDevices: "Outputs in cycle",
        soundOutputSwitcherNoAvailableSelection: "Select at least one available output.",
        mixerInputTitle: "Microphone",
        mixerInputNoDevices: "No microphones found",
        mixerInputUnavailable: "Microphone unavailable",
        mixerInputFallback: "Using default until this microphone returns.",
        mixerInputTooltip: "Choose microphone",
        mixerInputErrorFormat: "Could not switch: %@",
        mixerVisibleApps: "Apps in the list",
        mixerAllShown: "All",
        mixerHiddenCountLabel: "Hidden",
        mixerHideFromList: "Hide from the list",
        updatesSection: "Updates",
        autoCheckToggle: "Check for updates automatically",
        includeBetaUpdatesToggle: "Receive beta updates",
        includeBetaUpdatesCaption: "Beta versions include features in development and may contain bugs or incomplete behavior.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Check now",
        updateChecking: "Checking…",
        updateUpToDate: "You’re on the latest version.",
        updateAvailablePrefix: "Update available:",
        updateInstallButton: "Download and install",
        updateDownloading: "Downloading update…",
        updateInstalling: "Installing and restarting…",
        updateFailedPrefix: "Couldn’t check:",
        updateLastChecked: "Last checked:",
        updateNotifyTitle: "Vorssaint update",
        updateInstallFailedBody: "The update was downloaded but could not be applied. Download the latest version from the GitHub releases page and drag the app over the current one.",
        updateNeedsApplicationsTitle: "Move Vorssaint to Applications",
        updateNeedsApplicationsBody: "The app is running from a place that cannot be updated, such as the disk image or a temporary system location. Drag Vorssaint to the Applications folder, open it from there and try again.",
        menuCheckUpdates: "Check for updates…",
        permissionRequired: "Wymagane uprawnienie",
        permissionAccessibility: "Dostępność",
        permissionScreenRecording: "Nagrywanie ekranu",
        permissionGranted: "Przyznano",
        permissionMissing: "Brak",
        permissionOpenSettings: "Otwórz Ustawienia systemowe",
        permissionRequest: "Poproś o uprawnienie",
        permissionRestartNote: "Po zmianie uprawnień może być potrzebne ponowne uruchomienie aplikacji.",
        secureInputTitle: "Secure input is on",
        secureInputHeldFormat: "%@ is holding it, so Vorssaint cannot type for you. Dismiss its password field, or quit it, to release it.",
        secureInputUnattributed: "No running app claims it. Log out and back in to clear it.",
        secureInputUnidentified: "The app holding it could not be identified, so Vorssaint cannot type for you.",
        secureInputRevealFormat: "Show %@",
        aboutDescription: "Bezpłatny, niezależny zestaw narzędzi do paska menu dla macOS.",
        versionPrefix: "Wersja",
        reviewIntro: "Podoba Ci się Vorssaint? ⭐",
        reviewHighlights: "Zobacz, co nowego w najnowszej wersji.",
        viewOnGitHub: "Zobacz na GitHubie",
        obContinue: "Dalej",
        obBack: "Wstecz",
        obSkipStep: "Pomiń",
        obStart: "Rozpocznij",
        obStepWelcomeTitle: "Witaj w Vorssaint",
        obStepWelcomeBody: "Zestaw przydatnych narzędzi dostępnych z paska menu.",
        obWelcomeBullet1Title: "Energy under control",
        obWelcomeBullet1Body: "Keep the Mac awake for as long as you want, even with the lid closed.",
        obWelcomeBullet2Title: "A clear view of the system",
        obWelcomeBullet2Body: "CPU, GPU and battery temperatures, hardware usage and memory pressure in real time.",
        obWelcomeBullet3Title: "Mouse and windows, your way",
        obWelcomeBullet3Body: "Reversed mouse scrolling and a window switcher with thumbnails.",
        obLanguageLabel: "Język",
        obStepAccessibilityTitle: "Dostępność",
        obStepAccessibilityBody: "Vorssaint potrzebuje tego uprawnienia do sterowania oknami, skrótami i funkcjami systemowymi.",
        obAccessibilityWhy: "The app only watches the mouse wheel and the switcher shortcut. Nothing is recorded or sent anywhere.",
        obStepRecordingTitle: "Nagrywanie ekranu",
        obStepRecordingBody: "To uprawnienie jest potrzebne do podglądów okien i funkcji przechwytywania ekranu.",
        obRecordingWhy: "Thumbnails are generated on the fly, stay in memory and never leave your Mac. Without it, the switcher still works with icons.",
        obStepMonitorTitle: "System monitor",
        obStepMonitorBody: "The panel shows CPU, GPU and battery temperatures, hardware usage and memory pressure.",
        obMonitorNoPermission: "No permission needed. Sensors are read straight from the system.",
        obStepOptionalTitle: "Optional features",
        obStepOptionalBody: "Turn on what you want to use now. Everything can be changed later in Settings.",
        obStepStatusTitle: "Checkup",
        obStepStatusBody: "Make sure everything is ready for the features you want.",
        obStatusRecheck: "Check again",
        obStepDoneTitle: "Gotowe",
        obStepDoneBody: "Podstawowa konfiguracja jest zakończona.",
        obDoneHint: "Możesz zmienić wszystko później w Ustawieniach.",
        obWhatsNewTitle: "What’s new in this version",
        obWhatsNewFallback: "This update includes the latest fixes and improvements.",
        obLanguageUpdateTitle: "Now in your language",
        obLanguageUpdateBody: "Vorssaint now speaks several languages. Choose the one you’d like to use; you can change it anytime in Settings.",
        obPurposeTitle: "What brought you here?",
        obPurposeBody: "Choose a ready setup or select exactly what you want to use.",
        obPurposeSkip: "You can add or remove features later in Settings.",
        tabMonitor: "Monitor",
        monitorMenuBarSection: "Pasek menu",
        monitorMenuBarCaption: "Wybierz, co ma być pokazywane obok ikony aplikacji.",
        monitorCombineTemperatures: "Połącz temperatury",
        monitorCombineTemperaturesCaption: "Pokazuj temperatury CPU, GPU i baterii jako jeden element.",
        monitorSeparateMenuBarMetrics: "Oddziel metryki paska menu",
        monitorSeparateMenuBarMetricsCaption: "Pokazuj każdą metrykę osobno.",
        monitorNetworkUploadFirst: "Najpierw wysyłanie",
        monitorShowCPU: "Pokaż CPU",
        monitorShowMemory: "Pokaż pamięć",
        monitorShowNetwork: "Pokaż sieć",
        monitorShowPowerLabel: "Pokaż zasilanie",
        monitorIntervalLabel: "Częstotliwość odświeżania",
        monitorInterval1: "1 sekunda",
        monitorInterval2: "2 sekundy",
        monitorInterval5: "5 sekund",
        monitorPanelSection: "Panel monitora",
        panelNavigationMode: "Tryb nawigacji panelu",
        panelNavigationCaption: "Wybierz, czy panel działa sekcjami, czy jako jedna lista.",
        panelFooterSections: "Sekcje",
        panelFooterList: "Lista",
        betaBadge: "Beta",
        betaFeatureWarning: "Ta funkcja jest w wersji beta.",
        networkSection: "Sieć",
        networkIPAddresses: "Adresy IP",
        networkLocalIP: "Lokalny adres IP",
        networkDownload: "Pobieranie",
        networkUpload: "Wysyłanie",
        networkThisSession: "Ta sesja",
        networkMeasuring: "Pomiar…",
        networkApps: "Aktywność aplikacji",
        networkAppsIdle: "Brak aktywności",
        diskSection: "Dysk",
        diskUsed: "Zajęte",
        diskFree: "Wolne",
        diskMenuBarStyleLabel: "Styl w pasku menu",
        diskMenuBarUsedPercentage: "Procent zajętego miejsca",
        diskMenuBarAvailableSpace: "Dostępne miejsce",
        diskMenuBarUsedSpace: "Zajęte miejsce",
        diskAvailable: "Dostępne",
        diskPurgeable: "Możliwe do usunięcia",
        diskInternal: "Wewnętrzny",
        diskExternal: "Zewnętrzny",
        diskSelect: "Wybierz",
        diskRead: "Odczyt",
        diskWrite: "Zapis",
        diskSMARTStatus: "Stan SMART",
        diskSMARTUnavailable: "SMART niedostępny",
        diskTotalRead: "Łączny odczyt",
        diskTotalWritten: "Łączny zapis",
        diskTemperature: "Temperatura",
        diskHealth: "Kondycja",
        diskPowerCycles: "Cykle zasilania",
        diskPowerOnHours: "Godziny pracy",
        diskUnsafeShutdowns: "Nieprawidłowe wyłączenia",
        diskMediaErrors: "Błędy nośnika",
        diskEject: "Wysuń",
        diskEjectAll: "Wysuń wszystkie",
        diskEjecting: "Wysuwanie…",
        diskReadyToRemove: "Można bezpiecznie odłączyć",
        diskEjectFailed: "Nie udało się wysunąć",
        diskProtectionCaption: "Chroń dyski zewnętrzne przed przypadkowym odłączeniem.",
        diskNoExternal: "Brak dysków zewnętrznych",
        diskOpenInFinder: "Otwórz w Finderze",
        diskStorageSettings: "Ustawienia pamięci masowej",
        diskNoDisks: "Brak dysków",
        powerSection: "Zasilanie",
        powerSystem: "System",
        powerAdapter: "Zasilacz",
        powerBattery: "Bateria",
        powerCharging: "Ładowanie",
        powerOnBattery: "Z baterii",
        powerPluggedIn: "Podłączony do zasilania",
        powerUnavailable: "Niedostępne",
        powerAdapterMaxFormat: "Maks. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU temperature",
        monitorShowGPUTemperature: "GPU temperature",
        monitorShowBatteryTemperature: "Battery temperature",
        monitorShowPeripheralBattery: "Peripheral battery",
        peripheralBatteryNoDevices: "No devices found",
        monitorGraphsSection: "Graphs",
        monitorGraphsCaption: "Choose which metrics show a graph over time.",
        updateBannerTitle: "Update available",
        updateBannerAction: "Update",
        obStepMenuBarTitle: "Metrics in the menu bar",
        obStepMenuBarBody: "Pick what to show next to the icon. The preview above updates live.",
        obStepMenuBarNote: "New: Network and Power blocks and graphs in the panel. Fine-tune it all later in Settings › Monitor.",
        monitorMenuBarPresetLabel: "Style",
        menuBarPresetReadable: "Readable",
        menuBarPresetDense: "Dense",
        menuBarSpacingLabel: "Menu bar spacing",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Compact",
        menuBarHideIconToggle: "Hide the app icon while metrics are shown",
        menuBarHideIconCaption: "The icon returns by itself when metrics leave the bar and when there is something to signal (an update ready or the microphone muted).",
        monitorLabelStyleLabel: "Labels",
        menuBarLabelStyleCompact: "Compact",
        menuBarLabelStyleClassic: "Classic",
        monitorMemoryStyleLabel: "Show memory as",
        monitorMemoryPressureDot: "Pressure dot",
        memoryStyleDot: "Dot",
        memoryStylePercent: "%",
        memoryStyleBoth: "Both",
        systemUptime: "Czas działania",
        batteryCharge: "Poziom baterii",
        powerHealth: "Kondycja baterii",
        powerCycles: "Cykle",
        speedTestRun: "Test prędkości",
        speedTestAgain: "Testuj ponownie",
        speedTestLatency: "Opóźnienie",
        speedTestTesting: "Testowanie…",
        speedTestFailed: "Test nieudany",
        monitorShowInPanel: "Pokaż w panelu",
        disclosureExpanded: "Rozwinięte",
        disclosureCollapsed: "Zwinięte",
        panelHideItem: "Ukryj w panelu",
        panelShowItem: "Pokaż w panelu",
        panelHiddenItem: "Ukryte",
        monitorItemUptime: "Czas działania",
        monitorItemNetSpeed: "Bieżąca prędkość",
        monitorItemNetTotals: "Suma w tej sesji",
        monitorItemNetTest: "Test prędkości",
        monitorItemDiskUsage: "Użycie dysku",
        monitorItemDiskActivity: "Bieżąca aktywność",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Ochrona zewnętrznych dysków",
        monitorItemDiskTools: "Narzędzia",
        monitorPanelConfigHint: "Otwórz blok, aby wybrać, co ma pokazywać.",
        monitorOrderHint: "Przeciągaj, aby zmieniać kolejność sekcji panelu, i używaj oka, aby je pokazywać lub ukrywać.",
        obStepPanelTitle: "What’s in the panel",
        obStepPanelBody: "Open each block and pick exactly what shows when you click the icon.",
        obStepPanelNavigationTitle: "Section-based panel",
        obStepPanelNavigationBody: "The panel can now show one section at a time. You can switch between Sections and List in Settings.",
        cleaningMenuItem: "Tryb czyszczenia",
        utilitiesSection: "Narzędzia",
        quickControlsSection: "Sterowanie",
        panelCategoryWindows: "Okna",
        panelCategoryInput: "Mysz i klawiatura",
        panelCategoryFiles: "Pliki",
        windowMaximizeName: "Maksymalizuj okna",
        windowMaximizeCaption: "Zielony przycisk maksymalizuje okno bez tworzenia kolejnego biurka.",
        windowMaximizeActiveNow: "Nadpisanie zielonego przycisku aktywne",
        windowMaximizeNeedsAccessibility: "Wymaga uprawnienia Dostępność.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtruj powtórzenia klawiszy",
        keyDebounceCaption: "Filtruje bardzo szybkie powtórne naciśnięcia klawiszy.",
        keyDebounceActiveNow: "Filtr aktywny",
        keyDebounceGlobalWindow: "Okno globalne",
        keyDebouncePerKeySection: "Wybrane klawisze",
        keyDebouncePerKeyCaption: "Wartości dla poszczególnych klawiszy zastępują wartość globalną. Ustaw 0 ms, aby wyłączyć filtrowanie klawisza.",
        keyDebounceKeyLabel: "Klawisz",
        keyDebounceWindowLabel: "Okno czasowe",
        keyDebounceAddKey: "Dodaj klawisz",
        keyDebounceNoOverrides: "Brak ustawionych wyjątków.",
        keyDebounceRemoveKey: "Usuń klawisz",
        cleaningPanelCaption: "Blokuje klawiaturę, aby można było bezpiecznie ją wyczyścić.",
        cleaningOverlayTitle: "Klawiatura zablokowana do czyszczenia",
        cleaningOverlaySubtitle: "Naciśnij Escape 5 razy, aby odblokować",
        cleaningOverlayUnlock: "Odblokuj",
        cleaningOverlayMouseHint: "Mysz i gładzik nadal działają",
        cleaningKeepScreenVisibleToggle: "Pozostaw ekran widoczny",
        cleaningKeepScreenVisibleCaption: "Pokazuje dyskretny wskaźnik w rogu zamiast zaciemniać treść.",
        cleaningStartNow: "Zablokuj klawiaturę teraz",
        cleaningNeedsAxTitle: "Wymagany dostęp do Dostępności",
        cleaningNeedsAxBody: "Aby bezpiecznie zablokować klawiaturę, Vorssaint potrzebuje uprawnienia Dostępność. Przyznaj je w Ustawieniach systemowych i spróbuj ponownie.",
        tabSupport: "Wsparcie",
        shortcutsPageCaption: "Edytuj wszystkie globalne skróty funkcji zainstalowanych na tym Macu. Nieaktywne skróty pozostają zapisane, ale nie działają.",
        shortcutsPageTitle: "Skróty klawiaturowe",
        settingsSearchPlaceholder: "Szukaj w ustawieniach",
        donateHeading: "Pomóż rozwijać Vorssaint",
        donateMessage: "Vorssaint jest darmowy, niezależny i tworzony w wolnym czasie. Jeśli chcesz wesprzeć rozwój finansowo, Buy Me a Coffee pomaga mi dalej pracować nad aplikacją.",
        donateButton: "Wesprzyj na Buy Me a Coffee",
        donateThanks: "Dziękuję, że tu jesteś. 🖤",
        supportIntroTitle: "Pomóż rozwijać Vorssaint",
        supportIntroMessage: "Jeśli chcesz wesprzeć rozwój finansowo, jedynym miejscem do tego jest Buy Me a Coffee.",
        supportIntroStarButton: "Dodaj gwiazdkę Vorssaint na GitHubie",
        supportIntroStarMessage: "Wsparcie finansowe nie jest wymagane. Gwiazdka na GitHubie pomaga innym znaleźć Vorssaint i ma realne znaczenie dla rozwoju projektu.",
        supportIntroCoffeeButton: "Wesprzyj na Buy Me a Coffee",
        supportIntroLaterButton: "Nie teraz",
        supportIntroDoneButton: "Gotowe",
        discordIntroTitle: "Społeczność Vorssaint na Discordzie dopiero się rozwija",
        discordIntroMessage: "Społeczność Vorssaint jest nowa i dopiero powstaje. Dołącz wcześnie, poznaj innych użytkowników i pomóż tworzyć przyjazne miejsce wokół aplikacji.",
        discordIntroJoinButton: "Dołącz do społeczności Discord",
        communityIntroTitle: "Zobacz zanim zobaczą inni",
        communityIntroMessage: "Osoby, które obserwują mnie na X, widzą część zmian wcześniej. Pokazuję tam zapowiedzi tego, co nadchodzi, i jak to działa.",
        communityIntroFollowButton: "Obserwuj @vorssaint na X",
        homebrewOfficialIntroTitle: "Vorssaint w oficjalnym katalogu Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint można teraz instalować bezpośrednio z oficjalnego katalogu Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nowa instalacja",
        homebrewOfficialIntroMigrationTitle: "Używasz starego tapa?",
        homebrewOfficialIntroMigrationMessage: "Usuń tap raz. Aplikacja i ustawienia pozostaną na miejscu.",
        homebrewOfficialIntroCopyButton: "Kopiuj polecenie",
        updateShowcaseTitle: "Co nowego w 3.1.4",
        updateShowcaseMessage: "Zobacz najważniejsze ulepszenia w tej aktualizacji.",
        updateShowcaseUnavailable: "Film nie może się teraz załadować. Możesz mimo to kontynuować.",
        updateShowcaseRestart: "Uruchom ponownie",
        showMenuBarIcon: "Pokaż ikonę na pasku menu",
        menuBarIconStillHiddenTitle: "Ikona nadal jest ukryta",
        menuBarIconStillHiddenBody: "Ikona została odbudowana, ale macOS nie przydzielił jej widocznego miejsca. Pasek menu może być pełny: usuń część ikon lub zamknij aplikacje z długimi menu i spróbuj ponownie.",
        menuBarIconManagerHintFormat: "%@ is open and may be keeping the icon in its hidden section. Look for Vorssaint there, or set %@ to always show Vorssaint.",
        menuBarIconDisallowedBody: "macOS nie pozwala Vorssaint wyświetlać się na pasku menu. Otwórz Ustawienia systemowe → Pasek menu, znajdź Vorssaint na liście aplikacji i włącz „Pozwól na pasku menu”. Ikona pojawi się po włączeniu przełącznika.",
        shortcutRecording: "Naciśnij nowy skrót",
        shortcutReset: "Resetuj",
        shortcutNone: "Brak",
        shortcutClear: "Usuń skrót",
        shortcutInvalid: "Użyj co najmniej klawisza Control, Option lub Command wraz z klawiszem.",
        shortcutPressKeys: "Naciśnij klawisze",
        shortcutEscapeHint: "Escape anuluje.",
        shortcutDeleteHint: "Delete usuwa.",
        shortcutNotCaptured: "Nic nie zostało przechwycone. macOS lub inna aplikacja używa już tej kombinacji. Spróbuj innej.",
        shortcutConflictFormat: "Ten skrót jest już używany przez %@",
        shortcutTakeOverOffer: "macOS używa %@ do jednego ze swoich skrótów.",
        shortcutTakeOverAction: "Przejmij, gdy działa Vorssaint",
        shortcutTakeOverCaption: "macOS odzyskuje klawisz, gdy Vorssaint nie działa lub ta funkcja jest wyłączona.",
        shortcutTakeOverDismiss: "Nie przejmuj",
        shortcutUnavailable: "macOS odrzucił ten skrót. Wybierz inny.",
        shelfShortcutToggle: "Skrót półki",
        switcherUsageHintFormat: "Hold %@ to navigate; release to activate the window. Shift or ← goes back; W closes the window; Q quits the app; Esc cancels.",
        musicBlockSection: "Klawisze multimedialne",
        musicBlockTitle: "Zatrzymaj samoczynne otwieranie Muzyki",
        musicBlockCaption: "Blokuje otwieranie aplikacji muzycznej po wykryciu klawisza multimedialnego. Wymaga Dostępności. Polecenia słuchawkowe bez wykrytego klawisza pozostają bez zmian.",
        musicBlockUnavailable: "Ta ochrona jest teraz niedostępna. Wyłącz ją i włącz ponownie.",
        musicBlockReplacementLabel: "Otwórz zamiast tego",
        musicBlockReplacementNone: "Brak",
        musicBlockChooseApp: "Wybierz aplikację…",
        cleanerName: "Cleaner",
        cleanerIntroTitle: "Posprzątaj Maca",
        cleanerIntroCaption: "Skanuje pozostałości po odinstalowanych aplikacjach, pamięci podręczne, logi i Kosz. Wszystko sprawdzasz przed usunięciem, a elementy trafiają do Kosza.",
        cleanerScan: "Skanuj",
        cleanerScanning: "Skanowanie…",
        cleanerCleaning: "Czyszczenie…",
        cleanerCatLeftovers: "Pozostałości po odinstalowanych aplikacjach",
        cleanerCatLoginItems: "Osierocone elementy startowe",
        cleanerCatCaches: "Pamięć podręczna",
        cleanerCatLogs: "Logi",
        cleanerCatDeveloper: "Śmieci deweloperskie",
        cleanerCatTrash: "Kosz",
        cleanerLeftoversNote: "Znaleziono podczas analizy i pozostawiono odznaczone. Sprawdź ścieżkę przed zaznaczeniem.",
        cleanerLoginItemsNote: "Wpis zniknie z Elementów logowania po ponownym uruchomieniu Maca.",
        cleanerTrashNote: "Opróżnienie Kosza jest nieodwracalne.",
        cleanerCatDeviceBackups: "Kopie zapasowe iPhone’a",
        cleanerDeviceBackupsCaption: "Stare kopie iPhone’a i iPada zajmują dużą część pamięci, którą macOS określa jako Inne. Usuwaj tylko te, których już nie potrzebujesz.",
        cleanerNothingFound: "Nic do wyczyszczenia. Twój Mac jest uporządkowany.",
        cleanerClean: "Wyczyść",
        cleanerDoneNote: "Elementy trafiły do Kosza i można je stamtąd odzyskać.",
        cleanerAgain: "Skanuj ponownie",
        cleanerRevealInFinder: "Pokaż w Finderze",
        cleanerPanelCaption: "Pozostałości aplikacji, pamięć podręczna i logi",
        cleanerSafeSection: "Bezpieczne czyszczenie",
        cleanerOptionalSection: "Opcjonalne, wymagają sprawdzenia",
        cleanerCatOtherCaches: "Inne pamięci podręczne",
        cleanerCachesCaption: "Pliki tymczasowe, które aplikacje odtwarzają samodzielnie.",
        cleanerLogsCaption: "Stare logi diagnostyczne.",
        cleanerDeveloperCaption: "Pozostałości po kompilacjach Xcode i symulatorach.",
        cleanerLoginItemsCaption: "Elementy startowe pozostawione przez nieistniejące już aplikacje.",
        cleanerLeftoversCaption: "Pliki pozostawione przez odinstalowane aplikacje.",
        cleanerOtherCachesCaption: "Można bezpiecznie usunąć. Nic się nie zepsuje; aplikacje mogą tylko raz uruchomić się wolniej, a pobrane treści pobiorą się ponownie.",
        cleanerCleanSizeFormat: "Wyczyść %@",
        cleanerScheduleTitle: "Automatyczne czyszczenie",
        cleanerScheduleOff: "Wyłączone",
        cleanerScheduleDaily: "Codziennie",
        cleanerScheduleWeekly: "Co tydzień",
        cleanerScheduleCaption: "Automatycznie czyści tylko bezpieczną część o wybranej porze i przenosi wszystko do Kosza.",
        cleanerScheduleLastFormat: "Ostatnie automatyczne czyszczenie zwolniło %@.",
        cleanerAutoNotificationFormat: "Zwolniono %@ i przeniesiono do Kosza.",
        cleanerScheduleNextFormat: "Następne czyszczenie %@.",
        cleanerScheduleRanFormat: "Ostatnie automatyczne czyszczenie %@.",
        cleanerScheduleNotifyToggle: "Powiadamiaj po zakończeniu",
        cleanerNotifDenied: "Powiadomienia Vorssaint są wyłączone w systemie.",
        cleanerNotifOpenSettings: "Otwórz Ustawienia powiadomień…",
        launchAtLoginNeedsApplications: "Aplikacja działa z miejsca, którego nie można otwierać przy logowaniu. Przenieś Vorssaint do folderu Programy, uruchom stamtąd i włącz tę opcję ponownie.",
        launchAtLoginNeedsApproval: "Element logowania jest zarejestrowany, ale nadal wyłączony w Ustawieniach systemowych. Otwórz Ustawienia systemowe › Ogólne › Elementy logowania i rozszerzenia i włącz Vorssaint w sekcji Otwieraj przy logowaniu.",
        ocrRemoveLineBreaksToggle: "Usuń łamania wierszy",
        ocrRemoveLineBreaksCaption: "Usuwa podziały wierszy, aby skopiowany tekst wklejał się jako jeden akapit.",
        ocrQRToggle: "Odczytuj kody QR",
        ocrQRCaption: "Jeśli obszar zawiera kod QR, jego zawartość zostanie pokazana do skopiowania lub otwarcia.",
        ocrQRCopied: "Kod QR skopiowany",
        qrResultTitle: "Kod QR",
        qrResultCopy: "Kopiuj",
        qrResultOpen: "Otwórz link",
        highlightsTitle: "Nowości w tej aktualizacji",
        highlightsTitleClipboardRedesign: "Przeprojektowany schowek",
        highlightsTitleWindowLayout: "Układ okien",
        highlightsTitleQuitProtection: "Ochrona przed zamykaniem i kończeniem aplikacji",
        highlightsTitleRecorderBlur: "Rozmycie prywatnych danych podczas nagrywania",
        highlightsCaptionDockPreview: "Podgląd Docka działa teraz z włączonym powiększeniem Docka",
        highlightsCaptionScreenshot: "Narzędzie zrzutów ekranu dostało lupę pikselową i odczytywanie kodów QR",
        highlightsCaptionSnippetLibrary: "Przeszukiwane menu fragmentów wpisuje dowolny fragment bezpośrednio w miejscu kursora",
        highlightsCaptionCapturePalette: "Jeden skrót otwiera pływający panel zrzutów, nagrań, tekstu z ekranu i kolorów.",
        highlightsCaptionClipboardRedesign: "Clipboard history now opens as a compact palette with uncluttered rows and an on-demand preview for reading or editing the full item.",
        highlightsCaptionWindowLayout: "Position windows with the directional ring using a shortcut and pointer, or drag to screen edges to snap with custom gaps.",
        highlightsCaptionQuitProtection: "Avoid quitting apps or closing windows by accident with a hold, a double press or an extra modifier, customizable per app.",
        highlightsCaptionRecorderBlur: "Hide private details, passwords and sensitive areas anywhere across your recorded video before sharing or exporting.",
        highlightsConfigure: "Skonfiguruj",
        highlightsTry: "Wypróbuj",
        highlightsSeeAll: "Zobacz wszystkie zmiany",
        switcherCurrentSpaceOnly: "Pokaż tylko bieżące biurko",
        switcherCurrentSpaceOnlyCaption: "Pokazuje tylko okna z bieżącego biurka. Wybór okna nigdy nie przenosi na inne biurko.",
        shelfFileMissing: "Plik już nie istnieje",
        previewSizeSmall: "Mały",
        mixerSoundEffectsOutputTitle: "Dźwięki systemowe",
        mixerSoundEffectsOutputTooltip: "Wybierz, gdzie odtwarzać alerty i efekty dźwiękowe",
        monitorOpenActivityMonitor: "Otwórz Monitor aktywności",
        dockClickHide: "Kliknij ikonę Docka, aby ukryć aplikację",
        dockClickHideCaption: "Aktywna aplikacja ukrywa się po kliknięciu jej ikony w Docku. Kliknij ponownie, aby ją przywrócić.",
        monitorMemoryMetricLabel: "Mierz pamięć jako",
        memoryMetricUsed: "Użycie pamięci",
        memoryMetricApp: "Pamięć aplikacji",
        keepAwakeRightClickToggle: "Kliknij prawym przyciskiem ikonę paska menu, aby przełączać „Nie usypiaj”",
        keepAwakeRightClickToggleCaption: "Zastępuje menu kontekstowe prawego przycisku.",
        urlCleanerRulesTitle: "Reguły czyszczenia",
        urlCleanerRulesCaption: "A site attaches these parameters to its own share links to track where the link came from. Switched on, a name is removed when a link is cleaned; switched off, it stays. Names you add can be deleted.",
        urlCleanerRulesCoverageCaption: "The list covers a site’s different share paths (the web page, the app, a live room), which is why it is long; a real link usually carries only two to four of them.",
        urlCleanerRulesAllSites: "Wszystkie witryny",
        urlCleanerRulesCountSingular: "1 parametr",
        urlCleanerRulesCountPluralFormat: "%d parametrów",
        urlCleanerRulesAddSite: "Dodaj witrynę",
        urlCleanerRulesParameterPlaceholder: "Nazwa parametru",
        urlCleanerRulesMatchCaption: "Write the name to the left of the = , like utm_source. A name that matches takes that one parameter out of the link and leaves the rest as it was.",
        urlCleanerRulesAddButton: "Dodaj",
        urlCleanerRulesRemoveButton: "Usuń nazwę",
        urlCleanerRulesRemoveSiteButton: "Wyłącz wszystkie reguły dla tej witryny",
        urlCleanerRemovedFormat: "Usunięto %@",
        switcherSearchPin: "Przypnij wyszukiwanie klawiszem S",
        switcherSearchPinCaption: "S starts a search and pins the switcher open, so typing no longer produces special characters when your shortcut uses ⌥, and a search starting with Q or W no longer closes the window or quits the app by mistake.",
        invertVerticalScroll: "Odwróć przewijanie w pionie",
        invertHorizontalScroll: "Odwróć przewijanie w poziomie",
        scrollHorizontalName: "Przewijaj na boki przytrzymując klawisz",
        scrollHorizontalModifierLabel: "Klawisz modyfikujący",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Przytrzymaj tylko wybrany klawisz modyfikujący, aby przewijać kółkiem myszy w poziomie.",
        switcherShowShortcutHints: "Pokaż podpowiedzi skrótów",
        switcherShowShortcutHintsCaption: "Pokazuje skróty aplikacji i okien pod ikonami.",
        uninstallerHomebrewPackageFormat: "%@ zostanie również usunięty z Homebrew.",
        shelfEdgeToggle: "Otwieraj przy krawędzi ekranu",
        shelfEdgeCaption: "Przeciągnij plik do krawędzi ekranu, aby wysunąć półkę. Upuść albo cofnij, a półka się schowa.",
        focusFollowsMouseName: "Focus follows mouse",
        focusFollowsMouseCaption: "Focuses and raises the window under the pointer after a short pause.",
        focusFollowsMouseDelay: "Hover delay",
        switcherMinimizedPlacementLabel: "Minimized windows and hidden apps",
        switcherMinimizedPlacementNormal: "Normal ordering",
        switcherMinimizedPlacementEnd: "Place at end",
        switcherMinimizedPlacementHidden: "Hide",
        switcherShowFullscreenWindows: "Show fullscreen windows",
        switcherScreenPlacementLabel: "Show on",
        switcherScreenPlacementPointer: "Screen with the pointer",
        switcherScreenPlacementMenuBar: "Screen with the menu bar",
        switcherScreenPlacementActiveWindow: "Screen with the active window",
        switcherScreenPlacementCaption: "Which display the switcher opens on when more than one is connected.",
        switcherCurrentDisplayOnly: "Show only the current display",
        switcherCurrentDisplayOnlyCaption: "Lists only windows on the display under the pointer. If that display has no windows, the switcher does not open.",
        smoothScrollResponseLabel: "Response",
        smoothScrollCoastLabel: "Coast",
        mouseAccelerationName: "Disable mouse acceleration",
        mouseAccelerationCaption: "Removes pointer acceleration for connected mice. Your previous setting returns when this is turned off or Vorssaint quits.",
        shelfClearOnClose: "Clear when closed",
        shelfClearOnCloseCaption: "Empties the shelf only when you click its close button. Automatic hiding and collapsing keep the items."
    )
}
