// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

// Polish catalog. Entries not yet translated stay synchronized with the
// English source and are replaced in subsequent localization passes.
extension Strings {
    static let pl = Strings(
        statusIdleTooltip: "Vorssaint: normalny tryb uśpienia",
        statusActiveUntil: "Vorssaint: nie usypiaj do",
        statusActiveIndefinite: "Vorssaint: nie usypiaj bezterminowo",
        menuEnableAwake: "Włącz nieusypianie",
        menuDisableAwake: "Wyłącz nieusypianie",
        menuActivateFor: "Włącz na…",
        menuSettings: "Ustawienia…",
        menuAbout: "O Vorssaint",
        menuQuit: "Zakończ Vorssaint",
        menuHide: "Ukryj Vorssaint",
        menuHideOthers: "Ukryj pozostałe",
        menuShowAll: "Pokaż wszystkie",
        menuEdit: "Edycja",
        menuUndo: "Cofnij",
        menuRedo: "Ponów",
        actionClear: "Wyczyść",
        actionRemove: "Usuń",
        actionBack: "Wstecz",
        actionSearch: "Szukaj",
        actionMute: "Wycisz",
        actionUnmute: "Włącz dźwięk",
        actionPlay: "Odtwórz",
        actionPause: "Wstrzymaj",
        menuCut: "Wytnij",
        menuCopy: "Kopiuj",
        menuPaste: "Wklej",
        menuSelectAll: "Zaznacz wszystko",
        menuWindow: "Okno",
        menuMinimize: "Minimalizuj",
        menuZoom: "Powiększ",
        menuClose: "Zamknij",
        minutes15: "15 minut",
        minutes30: "30 minut",
        hour1: "1 godzina",
        hours2: "2 godziny",
        hours4: "4 godziny",
        hours8: "8 godzin",
        indefinitely: "Bezterminowo",
        indefinite: "Bezterminowo",
        panelSettings: "Ustawienia",
        panelQuit: "Zakończ",
        panelHotkeyHint: "Skrót przełącza",
        keepAwakeTitle: "Nie usypiaj",
        keepAwakeEndsIn: "Kończy się za",
        keepAwakeUntilDisabled: "Aktywne do wyłączenia",
        keepAwakeNormalRules: "Mac korzysta z normalnych zasad zasilania",
        keepAwakeUntilLabel: "Do",
        keepAwakeUntilStart: "Uruchom",
        keepAwakeOptions: "Opcje",
        keepAwakeMouseJiggle: "Poruszaj lekko kursorem",
        keepAwakeMouseJiggleCaption: "Podczas sesji lekko porusza kursorem w wybranym odstępie.",
        keepAwakeMouseJiggleInterval: "Odstęp",
        keepAwakeActiveIconLabel: "Aktywna ikona",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kawa",
        keepAwakeActiveIconEye: "Oko",
        keepAwakeActiveIconMoon: "Księżyc",
        keepAwakeActiveIconLight: "Żarówka",
        keepAwakeIconTintLabel: "Kolor aktywnej ikony",
        keepAwakeIconTintOrange: "Pomarańczowy",
        keepAwakeIconTintGreen: "Zielony",
        keepAwakeIconTintBlue: "Niebieski",
        keepAwakeIconTintPurple: "Fioletowy",
        keepAwakeIconTintPink: "Różowy",
        keepAwakeIconTintNone: "Bez koloru",
        durationLabel: "Czas trwania",
        clamshellTitle: "Nie usypiaj przy zamkniętej pokrywie",
        clamshellOnCaption: "Uśpienie jest całkowicie wyłączone. Zwróć uwagę na zasilanie.",
        clamshellNeedsSession: "Będzie stosowane, gdy „Nie usypiaj” jest aktywne.",
        clamshellReady: "Gotowe. Włącza się i wyłącza bez hasła",
        clamshellNeedsPassword: "Poprosi raz o hasło administratora",
        systemSection: "System",
        temperatures: "Temperatury",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Bateria",
        usageSection: "Użycie sprzętu",
        memorySection: "Pamięć",
        memoryPressure: "Presja pamięci",
        memorySwapUsed: "Użycie pamięci wymiany",
        memoryCompressed: "Skompresowana",
        memoryCachedFiles: "Pliki w pamięci podręcznej",
        pressureNormal: "Normalna",
        pressureWarning: "Ostrzeżenie",
        pressureCritical: "Krytyczna",
        monitorUnavailable: "Czujniki są niedostępne na tym Macu",
        energyAppsTitle: "Znaczące użycie energii",
        energyAppsIdle: "Brak znaczącego użycia energii",
        notifySessionEndedTitle: "Sesja zakończona",
        notifySessionEndedBody: "Czas minął. Mac wróci do normalnego uśpienia.",
        notifyBatteryTitle: "Vorssaint wyłączony",
        notifyBatteryBody: "Niski poziom baterii. Przywrócono normalne uśpienie, aby chronić baterię.",
        adminPromptClamshellOn: "Vorssaint potrzebuje hasła, aby utrzymać Maca aktywnego przy zamkniętej pokrywie.",
        adminPromptClamshellOff: "Vorssaint potrzebuje hasła, aby ponownie włączyć normalne uśpienie Maca.",
        adminPromptRecover: "Vorssaint został zamknięty przy wyłączonym uśpieniu Maca. Wprowadź hasło, aby przywrócić normalne uśpienie.",
        adminPromptUpdate: "Vorssaint potrzebuje hasła, aby zainstalować aktualizację.",
        adminPromptSudoersInstall: "Vorssaint utworzy ograniczoną regułę (tylko pmset disablesleep), która pozwoli przełączać tryb przy zamkniętej pokrywie bez pytania o hasło. Hasło będzie potrzebne tylko teraz.",
        adminPromptSudoersRemove: "Vorssaint usunie regułę pozwalającą na tryb przy zamkniętej pokrywie bez hasła.",
        settingsTitle: "Ustawienia Vorssaint",
        tabGeneral: "Ogólne",
        tabEnergy: "Zasilanie",
        tabMouse: "Mysz i gładzik",
        tabSwitcher: "Przełącznik",
        tabAdvanced: "Zaawansowane",
        tabAbout: "O aplikacji",
        tabReleaseNotes: "Nowości",
        releaseNotesOnUpdateToggle: "Pokazuj nowości po aktualizacji",
        minimalWindowPreviews: "Minimalne podglądy okien",
        minimalWindowPreviewsCaption: "Ukrywa tytuły, przyciski i dekoracyjne szczegóły w podglądach Docka i przełącznika. Zaznaczenie pozostaje widoczne.",
        previewSizeLabel: "Rozmiar podglądu",
        previewSizeNormal: "Normalny",
        previewSizeLarge: "Duży",
        previewSizeXLarge: "Bardzo duży",
        settingsGroupFeatures: "Funkcje",
        advancedResetSection: "Uprawnienia",
        advancedResetDescription: "Usuwa wszystkie uprawnienia przyznane Vorssaint, element logowania i regułę zamkniętej pokrywy. Przydatne przed ponowną konfiguracją lub odinstalowaniem. Aplikacja pozostaje zainstalowana.",
        advancedClearButton: "Wyczyść wszystkie uprawnienia",
        advancedCleared: "Uprawnienia wyczyszczone.",
        advancedClearFailed: "Nie udało się usunąć części uprawnień lub reguły zamkniętej pokrywy. Spróbuj ponownie i zaakceptuj prośbę o hasło, jeśli się pojawi.",
        advancedClearConfirmTitle: "Wyczyścić wszystkie uprawnienia?",
        advancedClearConfirmBody: "Funkcje wymagające uprawnień przestaną działać, dopóki nie przyznasz ich ponownie. Ustawienia zostaną zachowane.",
        advancedUninstallSection: "Odinstalowanie",
        advancedUninstallDescription: "Wykonuje powyższe czynności, usuwa ustawienia i przenosi Vorssaint do Kosza bez pozostawiania śladów. Po zakończeniu aplikacja zostanie zamknięta.",
        advancedUninstallButton: "Całkowicie odinstaluj Vorssaint",
        advancedUninstallConfirmTitle: "Odinstalować Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint wyczyści uprawnienia, usunie ustawienia i przeniesie się do Kosza, a następnie zakończy działanie. Nie można cofnąć tego z poziomu aplikacji, ale aplikacja pozostanie w Koszu do jego opróżnienia.",
        advancedUninstallFailedTitle: "Odinstalowanie przerwane",
        advancedUninstallFailedBody: "Vorssaint nie mógł przywrócić ustawienia systemowego, które zmienił: uśpienia, prędkości wentylatorów lub akceleracji myszy. Nic nie zostało usunięte.",
        launchAtLogin: "Uruchamiaj przy logowaniu",
        languageLabel: "Język",
        menuBarSection: "Pasek menu",
        showCountdown: "Pokazuj pozostały czas obok ikony",
        globalHotkeySection: "Skrót globalny",
        hotkeyToggle: "Włącz skrót „Nie usypiaj”",
        hotkeyCaption: "Działa w każdej aplikacji, bez dodatkowych uprawnień.",
        sessionSection: "Sesja",
        defaultDurationLabel: "Domyślny czas trwania",
        keepAwakeAutoStart: "Nie usypiaj po uruchomieniu Vorssaint",
        keepAwakeAutoStartCaption: "Uruchamia sesję z domyślnym czasem trwania.",
        batteryProtectionSection: "Ochrona baterii",
        batteryDisableBelow: "Wyłącz, gdy bateria spadnie poniżej",
        batteryNever: "Nigdy",
        batteryProtectionCaption: "Chroni MacBooka przed rozładowaniem przez zapomnianą sesję.",
        clamshellSection: "Zamknięta pokrywa",
        configuring: "Konfigurowanie…",
        sudoersFailed: "Nie udało się włączyć trybu zamkniętej pokrywy. Spróbuj ponownie.",
        clamshellExplanation: "„Nie usypiaj przy zamkniętej pokrywie” całkowicie wyłącza uśpienie, gdy „Nie usypiaj” jest aktywne, i automatycznie przywraca je po zakończeniu sesji lub zamknięciu aplikacji. Najlepiej używać po podłączeniu zasilania.",
        scrollSection: "Przewijanie",
        invertMouseScroll: "Odwróć przewijanie myszy",
        invertMouseScrollCaption: "Odwraca kierunek kółka myszy.",
        scrollTrackpadNote: "Gładzik pozostaje bez zmian: zachowuje naturalne przewijanie macOS.",
        scrollActiveNow: "Przewijanie myszy jest obecnie odwrócone",
        mouseNavigationActiveNow: "Przyciski boczne są teraz aktywne",
        smoothScrollName: "Płynne przewijanie",
        smoothScrollCaption: "Zamienia każdy krok kółka myszy na krótkie, płynne przesunięcie. Gładzik nie jest zmieniany.",
        smoothScrollStepLabel: "Szybkość przewijania",
        mouseNavigationSection: "Nawigacja",
        mouseNavigationEnable: "Używaj przycisków bocznych do Wstecz i Dalej",
        mouseNavigationCaption: "Zamienia przyciski Wstecz i Dalej myszy na polecenia nawigacji w Finderze, przeglądarkach i zgodnych aplikacjach.",
        middleClickSection: "Środkowy przycisk",
        middleClickEnable: "Kliknięcie trzema palcami działa jak środkowy przycisk",
        middleClickEnableCaption: "Naciśnięcie gładzika trzema palcami działa jak kliknięcie kółkiem myszy: otwiera linki w nowej karcie, zamyka karty i wykonuje inne działania środkowego przycisku.",
        middleClickDragConflict: "W macOS włączone jest przeciąganie trzema palcami i używa tego samego gestu. Wyłącz je w Ustawieniach systemowych w Dostępność → Sterowanie wskaźnikiem → Opcje gładzika, a środkowe kliknięcie będzie działać.",
        middleClickTapPicker: "Lekkie stuknięcie również klika",
        middleClickTapOff: "Wyłączone",
        middleClickTapThreeFingers: "3 palce",
        middleClickTapFourFingers: "4 palce",
        middleClickTapCaption: "Lekkie stuknięcie tyloma palcami, bez naciskania, również wykonuje środkowe kliknięcie. Przesuwanie nigdy się nie liczy. Jeśli stuknięcie trzema palcami w macOS jest przypisane do Wyszukiwania, wyłącz je, aby oba gesty nie uruchamiały się jednocześnie.",
        quickToolsTab: "Panel szybkich narzędzi",
        quickToolShortcutToggle: "Skrót globalny",
        ocrName: "Kopiuj tekst z ekranu",
        ocrCaption: "Zaznacz obszar ekranu, a rozpoznany tekst zostanie skopiowany i będzie gotowy do wklejenia.",
        ocrCopied: "Tekst skopiowany",
        ocrNoText: "Nie znaleziono tekstu",
        colorPickerName: "Próbnik kolorów",
        colorPickerCaption: "Wybierz kolor dowolnego piksela ekranu i skopiuj go w wybranym formacie.",
        colorPickerFormatLabel: "Format kopiowania",
        colorPickerBareHexToggle: "Kopiuj bez prefiksu #",
        colorPickerPickNow: "Wybierz kolor",
        micMuteName: "Wycisz mikrofon",
        micUnmuteName: "Włącz mikrofon",
        micMuteCaption: "Jednym kliknięciem lub skrótem wycisza mikrofon Maca we wszystkich aplikacjach.",
        micMutedHUD: "Mikrofon wyciszony",
        micUnmutedHUD: "Mikrofon włączony",
        micMutePartialHUD: "Nie udało się wyciszyć części mikrofonów",
        micUnmutePartialHUD: "Część mikrofonów nadal jest wyciszona",
        micMuteMenuBarToggle: "Pokazuj na pasku menu podczas wyciszenia",
        micMuteMenuBarCaption: "Czerwony przekreślony mikrofon pojawia się obok ikony aplikacji na pasku menu.",
        pastePlainName: "Wklej jako zwykły tekst",
        pastePlainCaption: "Wkleja skopiowaną treść bez kolorów, czcionek i formatowania. Oryginał pozostaje w schowku.",
        launcherName: "Panel szybkich narzędzi",
        launcherCaption: "Pływający panel z ulubionymi narzędziami, otwierany skrótem z dowolnego miejsca.",
        launcherOpenNow: "Otwórz panel szybkich narzędzi",
        launcherEditHint: "Użyj przycisku konfiguracji, aby wybierać, ukrywać i przeciągać narzędzia.",
        launcherEmptyState: "Wszystkie narzędzia są ukryte. Użyj przycisku konfiguracji, aby je przywrócić.",
        launcherAddSection: "Dodaj ponownie",
        launcherKeysHint: "Strzałki nawigują, Enter otwiera, 1–9 otwierają bezpośrednio",
        switcherSection: "Przełącznik aplikacji",
        switcherEnable: "Używaj przełącznika Vorssaint",
        switcherEnableCaption: "Przełączaj aplikacje i okna, także zminimalizowane oraz wiele okien tej samej aplikacji.",
        switcherUsageHint: "Przytrzymaj skrót, aby nawigować; zwolnij, aby aktywować okno. Shift lub ← cofa; W zamyka okno; Q kończy aplikację; Esc anuluje.",
        switcherNoWindows: "Brak otwartych okien",
        switcherIconRowMode: "Pokaż %@ z dużymi ikonami",
        switcherIconRowModeCaption: "Pokazuje jedną ikonę na aplikację oraz podglądy jej okien powyżej.",
        switcherSimpleModeCaption: "Pokazuje ikony aplikacji i tytuły okien bez podglądów i przechwytywania ekranu przez przełącznik.",
        switcherShortcutHintApps: "Aplikacje",
        switcherShortcutHintWindows: "Okna",
        switcherWindowShortcutCaption: "Otwiera przełącznik okien aplikacji znajdującej się na pierwszym planie. Gdy przełącznik aplikacji jest otwarty, przełącza między oknami wybranej aplikacji.",
        switcherTakeOverSystemShortcuts: "Zastąp ⌘Tab i ⌘` macOS",
        switcherTakeOverSystemShortcutsCaption: "Wyłącza odpowiednie skróty aplikacji i okien macOS tylko wtedy, gdy przełącznik Vorssaint jest aktywny. Wszystkie uruchomione aplikacje pozostają dostępne.",
        switcherAppearanceDelay: "Opóźnienie wyświetlania",
        switcherAppearanceDelayCaption: "Jak długo trzeba przytrzymać skrót, zanim pojawi się przełącznik.",
        switcherMergeTabs: "Pokazuj jeden wpis na aplikację",
        switcherMergeTabsCaption: "Łączy wszystkie okna aplikacji w jeden wpis zamiast osobnego wpisu dla każdego okna.",
        switcherWindowlessApps: "Aplikacje bez otwartego okna",
        switcherWindowlessAppsCaption: "Wybiera, które uruchomione aplikacje bez żadnego okna mają być widoczne w przełączniku.",
        switcherWindowlessAppsOff: "Nie pokazuj",
        switcherWindowlessAppsFinder: "Tylko Finder",
        switcherWindowlessAppsAll: "Wszystkie aplikacje",
        switcherNoOpenWindow: "Brak otwartego okna",
        switcherOtherDesktop: "Inne biurko",
        dockPreviewName: "Podgląd Docka",
        dockPreviewEnable: "Podglądaj okna z Docka",
        dockPreviewEnableCaption: "Najedź na otwartą aplikację w Docku, aby zobaczyć jej okna, a następnie kliknij wybrane.",
        dockPreviewCurrentSpaceOnlyCaption: "Po wyłączeniu pokazuje okna ze wszystkich biurek. Wybór okna z innego biurka przenosi na nie.",
        dockPreviewBackgroundOpacity: "Tło panelu",
        dockPreviewBackgroundOpacityCaption: "Zmniejsz krycie, aby zobaczyć więcej tego, co znajduje się za panelem.",
        dockPreviewOpenDelay: "Opóźnienie otwierania",
        dockPreviewOpenDelayCaption: "Jak długo wskaźnik musi pozostawać nad ikoną, zanim otworzy się jej panel.",
        dockPreviewQuitAppOnClose: "Zakończ aplikację przyciskiem ×",
        dockPreviewQuitAppOnCloseCaption: "W Podglądzie Docka przycisk × kończy całą aplikację zamiast zamykać tylko to okno.",
        dockPreviewKeepDockVisible: "Zachowaj Dock widoczny (eksperymentalne)",
        dockPreviewKeepDockVisibleCaption: "Wstrzymuje automatyczne ukrywanie Docka podczas otwartego podglądu i przywraca je po wyjściu. Może zmieniać rozmiar okien. Jeśli aplikacja zostanie przerwana, uruchom ją ponownie, aby przywrócić Dock.",
        dockPreviewOrderByCreation: "Sortuj okna według czasu utworzenia",
        dockPreviewOrderByCreationCaption: "Pokazuj starsze okna przed tymi używanymi ostatnio.",
        dockClickMinimize: "Kliknij ikonę Docka, aby zminimalizować",
        dockClickMinimizeCaption: "Okna aktywnej aplikacji są minimalizowane po kliknięciu jej ikony w Docku. Kliknij ponownie, aby je przywrócić.",
        dockClickCycleWindows: "Kliknij ikonę Docka, aby przełączać okna",
        dockClickCycleWindowsCaption: "Kliknij ikonę aktywnej aplikacji w Docku, aby przełączać jej okna jak przy ⌘`.",
        dockPreviewActiveNow: "Aktywne w Docku",
        dockPreviewDockUnavailable: "Nie udało się odczytać elementów Docka.",
        dockPreviewAutohideBeta: "Beta. Mogą wystąpić błędy.",
        dockPreviewOpenWindow: "Otwórz okno",
        dockPreviewCloseWindow: "Zamknij okno",
        dockPreviewMinimizeWindow: "Minimalizuj okno",
        dockPreviewRestoreWindow: "Przywróć okno",
        dockPreviewPinPanel: "Przypnij podgląd",
        dockPreviewUnpinPanel: "Odepnij podgląd",
        dockPreviewPinned: "Przypięte",
        dockPreviewClosePanel: "Zamknij podgląd",
        dockPreviewPreviousWindow: "Poprzednie okno",
        dockPreviewNextWindow: "Następne okno",
        cutPasteName: "Wytnij i wklej",
        cutPasteEnable: "Wycinaj i wklejaj pliki w Finderze",
        cutPasteEnableCaption: "Użyj ⌘X, aby wycinać, i ⌘V, aby przenosić pliki i foldery w Finderze.",
        cutPasteShowHUD: "Pokaż pływający panel",
        cutPasteShowHUDCaption: "Pokazuje wskaźnik z wyciętymi plikami, gdy Finder jest aktywny.",
        cutPasteHowTitle: "Jak używać",
        cutPasteStep1: "Zaznacz elementy w Finderze i naciśnij ⌘X, aby je wyciąć.",
        cutPasteStep2: "Otwórz folder docelowy i naciśnij ⌘V, aby je tam przenieść.",
        cutPasteTextNote: "W polach tekstowych, np. podczas zmiany nazwy, ⌘X i ⌘V nadal działają normalnie.",
        cutPasteActiveNow: "Gotowe do wycinania w Finderze",
        cutPasteAutomationNote: "Przy pierwszym użyciu macOS poprosi o zgodę na sterowanie Finderem.",
        cutReadyTitle: "Wycięto",
        cutReadyHint: "w folderze docelowym do przeniesienia",
        cutCancel: "Anuluj wycinanie",
        cutDoneTitle: "Przeniesiono!",
        cutMovedSingular: "1 element przeniesiony",
        cutMovedPluralFormat: "Przeniesiono %d elementów",
        cutSomeFailed: "Nie udało się przenieść części elementów",
        cutMovingTitle: "Przenoszenie…",
        cutMovingCountFormat: "%d z %d",
        autoQuitName: "Zakończ po zamknięciu",
        autoQuitEnable: "Zakończ aplikację po zamknięciu ostatniego okna",
        autoQuitEnableCaption: "Zamknięcie ostatniego okna aplikacji kończy również jej działanie.",
        autoQuitActiveNow: "Aktywne",
        autoQuitHowTitle: "Jak to działa",
        autoQuitStep1: "Zamknij ostatnie okno aplikacji (⌘W lub czerwonym przyciskiem).",
        autoQuitStep2: "Aplikacja zakończy działanie sama. Dialogi „Zachować zmiany?” nadal będą się pojawiać.",
        autoQuitPredictableNote: "Aplikacje, które zwykle działają bez okna, nigdy nie są kończone.",
        autoQuitExceptionsTitle: "Wyjątki",
        autoQuitExceptionsCaption: "Aplikacje z tej listy pozostają otwarte nawet bez okien.",
        autoQuitExceptionsEmpty: "Brak wyjątków",
        autoQuitAddApp: "Dodaj aplikację…",
        uninstallerName: "Odinstalator",
        uninstallerEnableCaption: "Usuwa aplikację razem z pozostawionymi przez nią pamięciami podręcznymi, ustawieniami, logami i resztkami.",
        uninstallerStep1: "Przeciągnij aplikację do Ustawień albo wybierz ją z listy.",
        uninstallerStep2: "Sprawdź znalezione pliki i zajmowane przez nie miejsce.",
        uninstallerStep3: "Przenieś wybrane elementy do Kosza. Nic nie jest trwale usuwane.",
        uninstallerMenuItem: "Odinstaluj aplikację…",
        uninstallerDropTitle: "Przeciągnij tutaj aplikację",
        uninstallerDropSubtitle: "albo wybierz ją do skanowania",
        uninstallerChoose: "Wybierz aplikację…",
        uninstallerPickerTitle: "Wybierz aplikację",
        uninstallerPickerSearch: "Szukaj aplikacji",
        uninstallerPickerEmpty: "Nie znaleziono aplikacji",
        uninstallerEmptyNote: "Nic nie zostanie usunięte bez Twojego potwierdzenia.",
        uninstallerFDANote: "Przyznaj Pełny dostęp do dysku, aby wykonać dokładniejsze skanowanie.",
        uninstallerFDAGrant: "Przyznaj dostęp…",
        uninstallerFDAHint: "Włącz Vorssaint na liście. Jeśli go tam nie ma, kliknij + i wybierz Vorssaint z folderu Programy. Dostęp zacznie działać po ponownym otwarciu aplikacji.",
        uninstallerFDARelaunch: "Uruchom ponownie teraz",
        uninstallerScanning: "Skanowanie plików…",
        uninstallerRemoving: "Przenoszenie do Kosza…",
        uninstallerFoundTitle: "znaleziono",
        uninstallerSelectedFormat: "Zaznaczono %d z %d",
        uninstallerRemove: "Przenieś do Kosza",
        uninstallerCancel: "Anuluj",
        uninstallerDoneTitle: "Gotowe!",
        uninstallerFreedFormat: "Odzyskano %@",
        uninstallerSomeFailed: "Nie udało się przenieść części elementów do Kosza.",
        uninstallerFailedNeedsFDA: "Dane aplikacji w piaskownicy można przenieść tylko przy pełnym dostępie do dysku. Hasło administratora go nie zastępuje.",
        uninstallerFailedMoreFormat: "i jeszcze %d",
        uninstallerAnother: "Odinstaluj kolejną",
        uninstallerCatApp: "Aplikacja",
        uninstallerCatSupport: "Wsparcie",
        uninstallerCatCaches: "Pamięć podręczna",
        uninstallerCatPreferences: "Ustawienia",
        uninstallerCatContainers: "Kontenery",
        uninstallerCatLogs: "Logi",
        uninstallerCatState: "Zapisany stan",
        uninstallerCatOther: "Inne",
        uninstallerCommandBarBrowseTitle: "Odinstaluj aplikację",
        uninstallerCommandBarToggle: "Pokaż w pasku poleceń",
        uninstallerCommandBarCaption: "Wybieraj i odinstalowuj aplikacje w pasku poleceń.",
        uninstallerCommandBarFinderTitle: "Odinstaluj aplikację zaznaczoną w Finderze",
        uninstallerSelectionUnavailable: "Wybierz aplikację, którą można usunąć w Finderze, albo wybierz inną z listy.",
        urlCleanerName: "Wyczyść adres URL",
        urlCleanerEnable: "Czyść adresy URL przy kopiowaniu",
        urlCleanerEnableCaption: "Usuwa parametry śledzące z linku, gdy tylko trafi on do schowka.",
        urlCleanerActiveNow: "Aktywne",
        urlCleanerManualTitle: "Wyczyść teraz",
        urlCleanerInputPlaceholder: "Wklej adres URL",
        urlCleanerOutputPlaceholder: "Oczyszczony adres URL pojawi się tutaj",
        urlCleanerCleanButton: "Wyczyść",
        urlCleanerPasteButton: "Wklej",
        urlCleanerCopyButton: "Kopiuj",
        urlCleanerClearButton: "Wyczyść pole",
        urlCleanerNoURL: "Wklej prawidłowy adres URL.",
        urlCleanerNoChange: "Nie ma nic do wyczyszczenia.",
        urlCleanerCleaned: "Adres URL wyczyszczony.",
        urlCleanerCopied: "Skopiowano.",
        urlCleanerLocalNote: "Lokalnie. Bez sieci.",
        homebrewName: "Homebrew",
        homebrewEnableCaption: "Szukaj, instaluj i usuwaj formuły oraz caski.",
        homebrewMissingTitle: "Nie znaleziono Homebrew",
        homebrewMissingBody: "Vorssaint może otworzyć Terminal z oficjalnym instalatorem Homebrew. Terminal pokaże kroki i poprosi o hasło, jeśli będzie potrzebne.",
        homebrewInstallHomebrew: "Zainstaluj Homebrew",
        homebrewInstallHomebrewCaption: "Po zakończeniu pracy Terminala wróć tutaj i kliknij Odśwież.",
        homebrewInstallHomebrewOpened: "Instalator został otwarty w Terminalu.",
        homebrewShellSetupTitle: "Dokończ konfigurację Terminala",
        homebrewShellSetupBody: "Homebrew jest zainstalowany, ale Terminal może jeszcze nie znać polecenia brew. Vorssaint może otworzyć Terminal z poleceniem konfiguracji.",
        homebrewShellSetupButton: "Skonfiguruj Terminal",
        homebrewShellSetupOpened: "Polecenie otwarto w Terminalu. Wróć tutaj i kliknij Odśwież.",
        homebrewRefresh: "Odśwież",
        homebrewCheckPackages: "Sprawdź pakiety",
        homebrewTrustTitle: "Tap nie jest jeszcze zaufany",
        homebrewTrustCaption: "Homebrew prosi teraz o potwierdzenie przed użyciem zewnętrznych tapów. Zaufaj %@, aby kontynuować.",
        homebrewTrustButton: "Zaufaj i kontynuuj",
        homebrewSearchPlaceholder: "Szukaj pakietów",
        homebrewKeyboardHint: "Spacja lub Return zamyka panel macOS. Użyj przycisku wyszukiwania.",
        homebrewSearchButton: "Szukaj",
        homebrewSearchResults: "Wyniki",
        homebrewInstalled: "Zainstalowane",
        homebrewAll: "Wszystkie",
        homebrewFormulas: "Formuły",
        homebrewCasks: "Caski",
        homebrewNoPackages: "Nie znaleziono pakietów",
        homebrewDependencies: "Zależności",
        homebrewNoSelection: "Wybierz zainstalowany pakiet albo wyszukaj nowy.",
        homebrewDetailsTitle: "Szczegóły pakietu",
        homebrewInstall: "Zainstaluj",
        homebrewUninstall: "Odinstaluj",
        homebrewUpgrade: "Aktualizuj",
        homebrewUpgradeAll: "Aktualizuj wszystkie",
        homebrewUpdateHomebrew: "Aktualizuj Homebrew",
        homebrewAllPackages: "pakietów",
        homebrewOpenTerminal: "Otwórz Terminal",
        homebrewCancelOperation: "Anuluj",
        homebrewClearLog: "Wyczyść dziennik",
        homebrewLogTitle: "Dziennik",
        homebrewVersion: "Wersja",
        homebrewDescription: "Typ",
        homebrewHomepage: "Otwórz stronę",
        homebrewPopularity: "Popularność",
        homebrewPopularityFormat: "%@ instalacji w ciągu %@ dni",
        homebrewInstalledBadge: "Zainstalowane",
        homebrewNotInstalledBadge: "Niezainstalowane",
        homebrewUpdates: "Aktualizacje",
        homebrewUpdateAvailableBadge: "Dostępna aktualizacja",
        homebrewLatestVersion: "Najnowsza",
        homebrewConfirmInstallTitle: "Zainstalować przez Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew pobierze i zainstaluje %@. Możliwe, że zostaną zainstalowane również zależności.",
        homebrewConfirmUninstallTitle: "Odinstalować przez Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew odinstaluje %@. Pliki konfiguracyjne mogą pozostać w systemie.",
        homebrewConfirmUpgradeTitle: "Zaktualizować przez Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew pobierze i zastosuje najnowszą wersję %@. Możliwe, że zostaną również zaktualizowane zależności.",
        homebrewConfirmUpgradeAllTitle: "Zaktualizować wszystkie przez Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew pobierze i zastosuje najnowsze wersje dostępne dla pakietów z aktualizacjami. Zależności mogą również zostać zaktualizowane.",
        homebrewConfirmUpdateHomebrewTitle: "Zaktualizować Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew pobierze najnowsze informacje, a następnie odświeży listę pakietów.",
        homebrewTerminalFallback: "Ta operacja wymaga Terminala do poproszenia o hasło administratora. Vorssaint nie przechwytuje haseł.",
        homebrewLoading: "Ładowanie…",
        homebrewSearchEmpty: "Brak wyników",
        homebrewOperationInstallFormat: "Instalowanie %@",
        homebrewOperationUninstallFormat: "Odinstalowywanie %@",
        homebrewOperationUpgradeFormat: "Aktualizowanie %@",
        homebrewOperationUpgradeAll: "Aktualizowanie pakietów",
        homebrewOperationUpdateHomebrew: "Aktualizowanie Homebrew",
        homebrewOperationInstalledFormat: "%@ zainstalowano.",
        homebrewOperationUninstalledFormat: "%@ odinstalowano.",
        homebrewOperationUpgradedFormat: "%@ zaktualizowano.",
        homebrewOperationUpgradedAll: "Pakiety zaktualizowane.",
        homebrewOperationUpdatedHomebrew: "Homebrew zaktualizowany.",
        homebrewOperationFailedFormat: "Nie udało się ukończyć %@.",
        homebrewOperationCancelled: "Operacja anulowana.",
        homebrewOperationPreparing: "Przygotowywanie…",
        homebrewOperationDownloading: "Pobieranie plików…",
        homebrewOperationInstalling: "Instalowanie plików…",
        homebrewOperationUninstalling: "Usuwanie plików…",
        homebrewOperationUpgrading: "Aktualizowanie plików…",
        homebrewOperationFinalizing: "Kończenie…",
        homebrewOperationRefreshing: "Odświeżanie listy…",
        homebrewOperationTerminal: "Kontynuuj w Terminalu.",
        homebrewOperationElapsedFormat: "Minęło %@",
        homebrewOperationShowDetails: "Pokaż szczegóły",
        homebrewOperationHideDetails: "Ukryj szczegóły",
        homebrewOperationTechnicalLog: "Szczegóły techniczne",
        homebrewOperationProgressUnknown: "Homebrew nie podał jeszcze wartości procentowej postępu.",
        mediaName: "Multimedia",
        mediaEnableCaption: "Kompresuj filmy, konwertuj i przetwarzaj obrazy, twórz GIF-y i wyodrębniaj tekst lokalnie.",
        mediaLocalNote: "Lokalnie. Bez sieci.",
        mediaToolVideo: "Wideo",
        mediaToolGIF: "GIF",
        mediaToolImage: "Obraz",
        mediaToolText: "Tekst",
        mediaSelectFile: "Wybierz plik",
        mediaDropHint: "Upuść tutaj plik albo kliknij, aby go wybrać.",
        mediaOutput: "Wyjście",
        mediaOutputAutomatic: "Automatycznie",
        mediaChooseOutput: "Miejsce docelowe",
        mediaStartVideo: "Kompresuj wideo",
        mediaStartGIF: "Utwórz GIF",
        mediaStartImage: "Przetwórz obraz",
        mediaStartConvertPDF: "Konwertuj do PDF",
        mediaStartText: "Wyodrębnij tekst",
        mediaCancel: "Anuluj",
        mediaStartTime: "Początek",
        mediaEndTime: "Koniec",
        mediaQuality: "Kompresja",
        mediaCompressionLow: "Niska",
        mediaCompressionMedium: "Średnia",
        mediaCompressionHigh: "Wysoka",
        mediaCompressionLowDescription: "Wysoka jakość, duży rozmiar pliku",
        mediaCompressionMediumDescription: "Zrównoważona jakość i rozmiar pliku",
        mediaCompressionHighDescription: "Niska jakość, mały rozmiar pliku",
        mediaMaxSize: "Rozmiar",
        mediaSizingResolution: "Rozdzielczość",
        mediaSizingFileSize: "Rozmiar pliku",
        mediaTargetSize: "Docelowy rozmiar",
        mediaTargetSizeHint: "Rozdzielczość zostanie dopasowana, aby pozostać poniżej limitu.",
        mediaErrorTargetTooSmall: "Docelowy rozmiar jest zbyt mały dla tego klipu. Skróć go albo zwiększ limit.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Szerokość",
        mediaFPS: "FPS",
        mediaKeepAudio: "Zachowaj dźwięk",
        mediaCodec: "Kodek",
        mediaFormat: "Format",
        mediaStripMetadata: "Usuń metadane",
        mediaLoopGIF: "Zapętl GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Dokładny",
        mediaOCRFast: "Szybki",
        mediaLanguageCorrection: "Korekta języka",
        mediaTextOutputNote: "Wyodrębniony tekst można skopiować i zapisać jako TXT.",
        mediaRunning: "Przetwarzanie",
        mediaCompleted: "Gotowe",
        mediaCancelled: "Anulowano.",
        mediaOpenInFinder: "Pokaż",
        mediaCopyText: "Kopiuj tekst",
        mediaRunAgain: "Uruchom ponownie",
        mediaEmptyText: "Nie znaleziono tekstu.",
        mediaResultSavedFormat: "Zapisano jako %@",
        mediaResultSizeFormat: "%@ do %@",
        mediaResultGrewCaption: "Przekonwertowany plik jest większy niż oryginał.",
        mediaErrorNoFile: "Najpierw wybierz plik.",
        mediaErrorNoVideo: "Ten plik nie zawiera ścieżki wideo.",
        mediaErrorSameOutput: "Wybierz miejsce docelowe inne niż oryginalny plik.",
        mediaErrorUnsupported: "Format nie jest obsługiwany przez macOS.",
        shelfName: "Półka",
        shelfEnable: "Tymczasowy obszar do przeciągania plików",
        shelfEnableCaption: "Pływające miejsce do gromadzenia plików, obrazów i tekstu, które można później przeciągać w dowolne miejsce.",
        shelfHowTitle: "Jak używać",
        shelfStep1: "Otwórz ją skrótem albo potrząśnij myszą podczas przeciągania.",
        shelfStep2: "Upuść na niej pliki, obrazy, linki lub tekst, aby je przechować.",
        shelfStep3: "Gdy będziesz ich potrzebować, przeciągnij każdy element z powrotem do dowolnej aplikacji.",
        shelfShakeToggle: "Otwieraj potrząśnięciem myszy podczas przeciągania",
        shelfShakeCaption: "Szybko potrząśnij wskaźnikiem podczas przeciągania elementu, aby przywołać półkę obok kursora.",
        shelfDropZoneToggle: "Przechowuj przeciągane pliki przy pasku menu",
        shelfDropZoneCaption: "Podczas przeciągania pliku półka pojawia się pod ikoną na pasku menu. Upuszczony element zostaje tam w przycisku, który można zmniejszyć i otworzyć kliknięciem; znika po opróżnieniu półki.",
        shelfDropZoneLabel: "Upuść tutaj",
        shelfCollapse: "Zwiń",
        shelfBehaviorTitle: "Po użyciu",
        shelfCloseAfterDrop: "Zamykaj po upuszczeniu do innej aplikacji",
        shelfCloseAfterDropCaption: "Zamyka półkę, gdy aplikacja docelowa przyjmie elementy. Przypięcie w panelu utrzymuje ją otwartą.",
        shelfRemoveAfterDrop: "Usuwaj elementy po upuszczeniu",
        shelfRemoveAfterDropCaption: "Elementy przyjęte przez inną aplikację znikają z półki. Wyłącz tę opcję, aby zachować kopię.",
        shelfExclusionsTitle: "Automatyczne wyjątki",
        shelfExclusionsEmpty: "Nie dodano aplikacji.",
        shelfExclusionsCaption: "Potrząśnięcie i strefa upuszczania przy pasku menu są wyłączone dla przeciągań rozpoczętych w tych aplikacjach. Skrót i Otwórz teraz nadal działają.",
        shelfPin: "Pozostaw otwartą",
        shelfUnpin: "Pozwól zamknąć po użyciu",
        extraBrightnessName: "Dodatkowa jasność",
        extraBrightnessCaption: "Wykorzystuje zapas HDR wyświetlacza, aby przekroczyć maksymalną jasność. Zużywa więcej baterii i może rozgrzewać Maca.",
        extraBrightnessLevelLabel: "Intensywność",
        extraBrightnessUnsupported: "Dostępne tylko na ekranach XDR, takich jak te w 14- i 16-calowych MacBookach Pro.",
        shelfHotkeyLabel: "Skrót",
        shelfOpenNow: "Otwórz teraz",
        shelfNoPermission: "Nie wymaga uprawnień.",
        shelfMenuItem: "Otwórz półkę",
        shelfTitle: "Półka",
        shelfEmpty: "Przeciągnij elementy tutaj",
        shelfClearAll: "Wyczyść wszystko",
        shelfRemoveSelected: "Usuń zaznaczone",
        shelfSelectedFormat: "Zaznaczono %d",
        shelfHint: "Kliknij, aby zaznaczyć. Przeciągnij na zewnątrz, aby użyć, albo kliknij prawym przyciskiem, aby zobaczyć więcej działań.",
        shelfItemImage: "Obraz",
        shelfTooltipItemsFormat: "%d elementów",
        shelfTooltipItemsFew: "%d elementy",
        shelfTooltipImageSingular: "%d obraz",
        shelfTooltipImageFew: "%d obrazy",
        shelfTooltipImagePlural: "%d obrazów",
        shelfTooltipFileSingular: "%d plik",
        shelfTooltipFileFew: "%d pliki",
        shelfTooltipFilePlural: "%d plików",
        shelfTooltipNoteSingular: "%d notatka",
        shelfTooltipNoteFew: "%d notatki",
        shelfTooltipNotePlural: "%d notatek",
        shelfTooltipLinkSingular: "%d link",
        shelfTooltipLinkFew: "%d linki",
        shelfTooltipLinkPlural: "%d linków",
        shelfActionOpen: "Otwórz",
        shelfActionOpenWith: "Otwórz za pomocą",
        shelfActionShare: "Udostępnij",
        breakdownMeasuring: "Pomiar…",
        mixerSection: "Mikser głośności",
        mixerEmpty: "Tutaj pojawią się aplikacje używające dźwięku",
        mixerUnavailable: "Dostępne w macOS 14.4 i nowszych",
        mixerPermissionBody: "Aby regulować głośność poszczególnych aplikacji, zezwól na „Nagrywanie ekranu i dźwięku systemowego” w Ustawieniach systemowych. Dźwięk nigdy nie jest nagrywany.",
        mixerResetTooltip: "Resetuj do 100%",
        mixerOutputDefault: "Domyślne",
        mixerOutputCurrent: "bieżące",
        mixerOutputUnavailable: "Wyjście niedostępne",
        mixerOutputFallback: "Po odłączeniu tego urządzenia używane będzie domyślne wyjście.",
        mixerBypassedCaption: "Ta aplikacja zarządza własnym dźwiękiem.",
        mixerOutputTooltip: "Wybierz wyjście",
        mixerSystemOutputTitle: "Wyjście",
        mixerSystemOutputNoDevices: "Nie znaleziono wyjść",
        mixerSystemOutputTooltip: "Wybierz wyjście systemowe",
        mixerSystemOutputErrorFormat: "Nie udało się przełączyć: %@",
        mixerLowerOnHeadphonesDisconnect: "Zmniejszaj głośność po odłączeniu słuchawek",
        mixerLowerOnHeadphonesDisconnectCaption: "Dostosowuje wyjście po odłączeniu słuchawek przewodowych lub Bluetooth.",
        mixerHeadphonesDisconnectVolume: "Głośność po odłączeniu",
        preciseVolumeRollerEnable: "Używaj dokładniejszych kroków głośności",
        preciseVolumeRollerCaption: "Zamienia pokrętła i klawisze głośności na mniejsze kroki systemowej głośności.",
        preciseVolumeRollerTapFailed: "Nie udało się nasłuchiwać klawiszy głośności.",
        soundOutputSwitcherTitle: "Przełącznik wyjścia",
        soundOutputSwitcherEnable: "Przełączaj wyjścia skrótem",
        soundOutputSwitcherCaption: "Wybierz wyjścia i użyj skrótu, aby przejść do następnego dostępnego.",
        soundOutputSwitcherDevices: "Wyjścia w cyklu",
        soundOutputSwitcherNoAvailableSelection: "Wybierz co najmniej jedno dostępne wyjście.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Nie znaleziono mikrofonów",
        mixerInputUnavailable: "Mikrofon niedostępny",
        mixerInputFallback: "Po odłączeniu tego mikrofonu używane będzie domyślne wejście.",
        mixerInputTooltip: "Wybierz mikrofon",
        mixerInputErrorFormat: "Nie udało się przełączyć: %@",
        mixerVisibleApps: "Aplikacje na liście",
        mixerAllShown: "Wszystkie",
        mixerHiddenCountLabel: "Ukryte",
        mixerHideFromList: "Ukryj na liście",
        updatesSection: "Aktualizacje",
        autoCheckToggle: "Sprawdzaj aktualizacje automatycznie",
        includeBetaUpdatesToggle: "Otrzymuj aktualizacje beta",
        includeBetaUpdatesCaption: "Wersje beta zawierają funkcje w trakcie rozwoju i mogą zawierać błędy lub niepełne działanie.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Sprawdź teraz",
        updateChecking: "Sprawdzanie…",
        updateUpToDate: "Masz najnowszą wersję.",
        updateAvailablePrefix: "Dostępna aktualizacja:",
        updateInstallButton: "Pobierz i zainstaluj",
        updateDownloading: "Pobieranie aktualizacji…",
        updateInstalling: "Instalowanie i ponowne uruchamianie…",
        updateFailedPrefix: "Nie udało się sprawdzić:",
        updateLastChecked: "Ostatnio sprawdzono:",
        updateNotifyTitle: "Aktualizacja Vorssaint",
        updateInstallFailedBody: "Aktualizacja została pobrana, ale nie udało się jej zastosować. Pobierz najnowszą wersję ze strony wydań GitHuba i przeciągnij aplikację na obecną wersję.",
        updateNeedsApplicationsTitle: "Przenieś Vorssaint do Programów",
        updateNeedsApplicationsBody: "Aplikacja działa z miejsca, którego nie można aktualizować, np. obrazu dysku lub tymczasowej lokalizacji systemowej. Przenieś Vorssaint do folderu Programy, uruchom stamtąd i spróbuj ponownie.",
        menuCheckUpdates: "Sprawdź aktualizacje…",
        permissionRequired: "Wymagane uprawnienie",
        permissionAccessibility: "Dostępność",
        permissionScreenRecording: "Nagrywanie ekranu",
        permissionGranted: "Przyznano",
        permissionMissing: "Brak",
        permissionOpenSettings: "Otwórz Ustawienia systemowe",
        permissionRequest: "Poproś o uprawnienie",
        permissionRestartNote: "Po zmianie uprawnień może być potrzebne ponowne uruchomienie aplikacji.",
        secureInputTitle: "Włączone bezpieczne wprowadzanie",
        secureInputHeldFormat: "%@ je przechwytuje, więc Vorssaint nie może pisać za Ciebie. Zamknij jego pole hasła albo zakończ aplikację, aby zwolnić blokadę.",
        secureInputUnattributed: "Żadna uruchomiona aplikacja nie zgłasza blokady. Wyloguj się i zaloguj ponownie, aby ją usunąć.",
        secureInputUnidentified: "Nie udało się zidentyfikować aplikacji, która ją przechwytuje, więc Vorssaint nie może pisać za Ciebie.",
        secureInputRevealFormat: "Pokaż %@",
        aboutDescription: "Bezpłatny, niezależny zestaw narzędzi do paska menu dla macOS.",
        versionPrefix: "Wersja",
        reviewIntro: "Podoba Ci się Vorssaint? ⭐",
        reviewHighlights: "Zobacz, co nowego w najnowszej wersji.",
        viewOnGitHub: "Zobacz na GitHubie",
        obContinue: "Dalej",
        obBack: "Wstecz",
        obSkipStep: "Pomiń",
        obStart: "Rozpocznij",
        obStepWelcomeTitle: "Witaj w Vorssaint",
        obStepWelcomeBody: "Zestaw przydatnych narzędzi dostępnych z paska menu.",
        obWelcomeBullet1Title: "Energia pod kontrolą",
        obWelcomeBullet1Body: "Nie usypiaj Maca tak długo, jak chcesz, nawet przy zamkniętej pokrywie.",
        obWelcomeBullet2Title: "Czytelny obraz systemu",
        obWelcomeBullet2Body: "Temperatury CPU, GPU i baterii, użycie sprzętu oraz presja pamięci w czasie rzeczywistym.",
        obWelcomeBullet3Title: "Mysz i okna po Twojemu",
        obWelcomeBullet3Body: "Odwrócone przewijanie myszy i przełącznik okien z miniaturami.",
        obLanguageLabel: "Język",
        obStepAccessibilityTitle: "Dostępność",
        obStepAccessibilityBody: "Vorssaint potrzebuje tego uprawnienia do sterowania oknami, skrótami i funkcjami systemowymi.",
        obAccessibilityWhy: "Aplikacja obserwuje tylko kółko myszy i skrót przełącznika. Nic nie jest nagrywane ani wysyłane.",
        obStepRecordingTitle: "Nagrywanie ekranu",
        obStepRecordingBody: "To uprawnienie jest potrzebne do podglądów okien i funkcji przechwytywania ekranu.",
        obRecordingWhy: "Miniatury są tworzone na bieżąco, pozostają w pamięci i nigdy nie opuszczają Maca. Bez tego uprawnienia przełącznik nadal działa z ikonami.",
        obStepMonitorTitle: "Monitor systemu",
        obStepMonitorBody: "Panel pokazuje temperatury CPU, GPU i baterii, użycie sprzętu oraz presję pamięci.",
        obMonitorNoPermission: "Nie są potrzebne żadne uprawnienia. Czujniki są odczytywane bezpośrednio z systemu.",
        obStepOptionalTitle: "Opcjonalne funkcje",
        obStepOptionalBody: "Włącz teraz to, czego chcesz używać. Wszystko można później zmienić w Ustawieniach.",
        obStepStatusTitle: "Kontrola",
        obStepStatusBody: "Sprawdź, czy wszystko jest gotowe do użycia wybranych funkcji.",
        obStatusRecheck: "Sprawdź ponownie",
        obStepDoneTitle: "Gotowe",
        obStepDoneBody: "Podstawowa konfiguracja jest zakończona.",
        obDoneHint: "Możesz zmienić wszystko później w Ustawieniach.",
        obWhatsNewTitle: "Co nowego w tej wersji",
        obWhatsNewFallback: "Ta aktualizacja zawiera najnowsze poprawki i ulepszenia.",
        obLanguageUpdateTitle: "Teraz w Twoim języku",
        obLanguageUpdateBody: "Vorssaint obsługuje teraz kilka języków. Wybierz ten, którego chcesz używać; możesz zmienić go w dowolnym momencie w Ustawieniach.",
        obPurposeTitle: "Co Cię tu sprowadza?",
        obPurposeBody: "Wybierz gotową konfigurację albo dokładnie to, czego chcesz używać.",
        obPurposeSkip: "Funkcje można później dodawać i usuwać w Ustawieniach.",
        tabMonitor: "Monitor",
        monitorMenuBarSection: "Pasek menu",
        monitorMenuBarCaption: "Wybierz, co ma być pokazywane obok ikony aplikacji.",
        monitorCombineTemperatures: "Połącz temperatury",
        monitorCombineTemperaturesCaption: "Pokazuj temperatury CPU, GPU i baterii jako jeden element.",
        monitorSeparateMenuBarMetrics: "Oddziel metryki paska menu",
        monitorSeparateMenuBarMetricsCaption: "Pokazuj każdą metrykę osobno.",
        monitorNetworkUploadFirst: "Najpierw wysyłanie",
        monitorShowCPU: "Pokaż CPU",
        monitorShowMemory: "Pokaż pamięć",
        monitorShowNetwork: "Pokaż sieć",
        monitorShowPowerLabel: "Pokaż zasilanie",
        monitorIntervalLabel: "Częstotliwość odświeżania",
        monitorInterval1: "1 sekunda",
        monitorInterval2: "2 sekundy",
        monitorInterval5: "5 sekund",
        monitorPanelSection: "Panel monitora",
        panelNavigationMode: "Tryb nawigacji panelu",
        panelNavigationCaption: "Wybierz, czy panel działa sekcjami, czy jako jedna lista.",
        panelFooterSections: "Sekcje",
        panelFooterList: "Lista",
        betaBadge: "Beta",
        betaFeatureWarning: "Ta funkcja jest w wersji beta.",
        networkSection: "Sieć",
        networkIPAddresses: "Adresy IP",
        networkLocalIP: "Lokalny adres IP",
        networkDownload: "Pobieranie",
        networkUpload: "Wysyłanie",
        networkThisSession: "Ta sesja",
        networkMeasuring: "Pomiar…",
        networkApps: "Aktywność aplikacji",
        networkAppsIdle: "Brak aktywności",
        diskSection: "Dysk",
        diskUsed: "Zajęte",
        diskFree: "Wolne",
        diskMenuBarStyleLabel: "Styl w pasku menu",
        diskMenuBarUsedPercentage: "Procent zajętego miejsca",
        diskMenuBarAvailableSpace: "Dostępne miejsce",
        diskMenuBarUsedSpace: "Zajęte miejsce",
        diskAvailable: "Dostępne",
        diskPurgeable: "Możliwe do usunięcia",
        diskInternal: "Wewnętrzny",
        diskExternal: "Zewnętrzny",
        diskSelect: "Wybierz",
        diskRead: "Odczyt",
        diskWrite: "Zapis",
        diskSMARTStatus: "Stan SMART",
        diskSMARTUnavailable: "SMART niedostępny",
        diskTotalRead: "Łączny odczyt",
        diskTotalWritten: "Łączny zapis",
        diskTemperature: "Temperatura",
        diskHealth: "Kondycja",
        diskPowerCycles: "Cykle zasilania",
        diskPowerOnHours: "Godziny pracy",
        diskUnsafeShutdowns: "Nieprawidłowe wyłączenia",
        diskMediaErrors: "Błędy nośnika",
        diskEject: "Wysuń",
        diskEjectAll: "Wysuń wszystkie",
        diskEjecting: "Wysuwanie…",
        diskReadyToRemove: "Można bezpiecznie odłączyć",
        diskEjectFailed: "Nie udało się wysunąć",
        diskProtectionCaption: "Chroń dyski zewnętrzne przed przypadkowym odłączeniem.",
        diskNoExternal: "Brak dysków zewnętrznych",
        diskOpenInFinder: "Otwórz w Finderze",
        diskStorageSettings: "Ustawienia pamięci masowej",
        diskNoDisks: "Brak dysków",
        powerSection: "Zasilanie",
        powerSystem: "Zasilanie systemowe",
        powerAdapter: "Zasilacz",
        powerBattery: "Bateria",
        powerCharging: "Ładowanie",
        powerOnBattery: "Z baterii",
        powerPluggedIn: "Podłączony do zasilania",
        powerUnavailable: "Niedostępne",
        powerAdapterMaxFormat: "Maks. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura CPU",
        monitorShowGPUTemperature: "Temperatura GPU",
        monitorShowBatteryTemperature: "Temperatura baterii",
        monitorShowPeripheralBattery: "Bateria urządzeń peryferyjnych",
        peripheralBatteryNoDevices: "Nie znaleziono urządzeń",
        monitorGraphsSection: "Wykresy",
        monitorGraphsCaption: "Wybierz metryki, dla których ma być pokazywany wykres w czasie.",
        updateBannerTitle: "Dostępna aktualizacja",
        updateBannerAction: "Aktualizuj",
        obStepMenuBarTitle: "Metryki na pasku menu",
        obStepMenuBarBody: "Wybierz, co ma być pokazywane obok ikony. Podgląd powyżej aktualizuje się na żywo.",
        obStepMenuBarNote: "Nowość: bloki Sieć i Zasilanie oraz wykresy w panelu. Później dostosujesz wszystko w Ustawieniach › Monitor.",
        monitorMenuBarPresetLabel: "Styl",
        menuBarPresetReadable: "Czytelny",
        menuBarPresetDense: "Gęsty",
        menuBarSpacingLabel: "Odstępy na pasku menu",
        menuBarSpacingStandard: "Standardowe",
        menuBarSpacingCompact: "Kompaktowe",
        menuBarHideIconToggle: "Ukryj ikonę aplikacji podczas wyświetlania metryk",
        menuBarHideIconCaption: "Ikona wraca sama, gdy metryki znikną z paska oraz gdy trzeba coś zasygnalizować, np. gotową aktualizację lub wyciszony mikrofon.",
        monitorLabelStyleLabel: "Etykiety",
        menuBarLabelStyleCompact: "Kompaktowe",
        menuBarLabelStyleClassic: "Klasyczne",
        monitorMemoryStyleLabel: "Pokazuj pamięć jako",
        monitorMemoryPressureDot: "Wskaźnik presji pamięci",
        memoryStyleDot: "Kropka",
        memoryStylePercent: "%",
        memoryStyleBoth: "Oba",
        systemUptime: "Czas działania",
        batteryCharge: "Poziom baterii",
        powerHealth: "Kondycja baterii",
        powerCycles: "Cykle",
        speedTestRun: "Test prędkości",
        speedTestAgain: "Testuj ponownie",
        speedTestLatency: "Opóźnienie",
        speedTestTesting: "Testowanie…",
        speedTestFailed: "Test nieudany",
        monitorShowInPanel: "Pokaż w panelu",
        disclosureExpanded: "Rozwinięte",
        disclosureCollapsed: "Zwinięte",
        panelHideItem: "Ukryj w panelu",
        panelShowItem: "Pokaż w panelu",
        panelHiddenItem: "Ukryte",
        monitorItemUptime: "Czas działania",
        monitorItemNetSpeed: "Bieżąca prędkość",
        monitorItemNetTotals: "Suma w tej sesji",
        monitorItemNetTest: "Test prędkości",
        monitorItemDiskUsage: "Użycie dysku",
        monitorItemDiskActivity: "Bieżąca aktywność",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Ochrona zewnętrznych dysków",
        monitorItemDiskTools: "Narzędzia",
        monitorPanelConfigHint: "Otwórz blok, aby wybrać, co ma pokazywać.",
        monitorOrderHint: "Przeciągaj, aby zmieniać kolejność sekcji panelu, i używaj oka, aby je pokazywać lub ukrywać.",
        obStepPanelTitle: "Co jest w panelu",
        obStepPanelBody: "Otwórz każdy blok i wybierz dokładnie to, co ma być pokazywane po kliknięciu ikony.",
        obStepPanelNavigationTitle: "Panel oparty na sekcjach",
        obStepPanelNavigationBody: "Panel może teraz pokazywać jedną sekcję naraz. W Ustawieniach możesz przełączać między Sekcjami a Listą.",
        cleaningMenuItem: "Tryb czyszczenia",
        utilitiesSection: "Narzędzia",
        quickControlsSection: "Sterowanie",
        panelCategoryWindows: "Okna",
        panelCategoryInput: "Mysz i klawiatura",
        panelCategoryFiles: "Pliki",
        windowMaximizeName: "Maksymalizuj okna",
        windowMaximizeCaption: "Zielony przycisk maksymalizuje okno bez tworzenia kolejnego biurka.",
        windowMaximizeActiveNow: "Nadpisanie zielonego przycisku aktywne",
        windowMaximizeNeedsAccessibility: "Wymaga uprawnienia Dostępność.",
        keyDebounceName: "Filtr powtórzeń",
        keyDebounceEnable: "Filtruj powtórzenia klawiszy",
        keyDebounceCaption: "Filtruje bardzo szybkie powtórne naciśnięcia klawiszy.",
        keyDebounceActiveNow: "Filtr aktywny",
        keyDebounceGlobalWindow: "Okno globalne",
        keyDebouncePerKeySection: "Wybrane klawisze",
        keyDebouncePerKeyCaption: "Wartości dla poszczególnych klawiszy zastępują wartość globalną. Ustaw 0 ms, aby wyłączyć filtrowanie klawisza.",
        keyDebounceKeyLabel: "Klawisz",
        keyDebounceWindowLabel: "Okno czasowe",
        keyDebounceAddKey: "Dodaj klawisz",
        keyDebounceNoOverrides: "Brak ustawionych wyjątków.",
        keyDebounceRemoveKey: "Usuń klawisz",
        cleaningPanelCaption: "Blokuje klawiaturę, aby można było bezpiecznie ją wyczyścić.",
        cleaningOverlayTitle: "Klawiatura zablokowana do czyszczenia",
        cleaningOverlaySubtitle: "Naciśnij Escape 5 razy, aby odblokować",
        cleaningOverlayUnlock: "Odblokuj",
        cleaningOverlayMouseHint: "Mysz i gładzik nadal działają",
        cleaningKeepScreenVisibleToggle: "Pozostaw ekran widoczny",
        cleaningKeepScreenVisibleCaption: "Pokazuje dyskretny wskaźnik w rogu zamiast zaciemniać treść.",
        cleaningStartNow: "Zablokuj klawiaturę teraz",
        cleaningNeedsAxTitle: "Wymagany dostęp do Dostępności",
        cleaningNeedsAxBody: "Aby bezpiecznie zablokować klawiaturę, Vorssaint potrzebuje uprawnienia Dostępność. Przyznaj je w Ustawieniach systemowych i spróbuj ponownie.",
        tabSupport: "Wsparcie",
        shortcutsPageCaption: "Edytuj wszystkie globalne skróty funkcji zainstalowanych na tym Macu. Nieaktywne skróty pozostają zapisane, ale nie działają.",
        shortcutsPageTitle: "Skróty klawiaturowe",
        settingsSearchPlaceholder: "Szukaj w ustawieniach",
        donateHeading: "Pomóż rozwijać Vorssaint",
        donateMessage: "Vorssaint jest darmowy, niezależny i tworzony w wolnym czasie. Jeśli chcesz wesprzeć rozwój finansowo, Buy Me a Coffee pomaga mi dalej pracować nad aplikacją.",
        donateButton: "Wesprzyj na Buy Me a Coffee",
        donateThanks: "Dziękuję, że tu jesteś. 🖤",
        supportIntroTitle: "Pomóż rozwijać Vorssaint",
        supportIntroMessage: "Jeśli chcesz wesprzeć rozwój finansowo, jedynym miejscem do tego jest Buy Me a Coffee.",
        supportIntroStarButton: "Dodaj gwiazdkę Vorssaint na GitHubie",
        supportIntroStarMessage: "Wsparcie finansowe nie jest wymagane. Gwiazdka na GitHubie pomaga innym znaleźć Vorssaint i ma realne znaczenie dla rozwoju projektu.",
        supportIntroCoffeeButton: "Wesprzyj na Buy Me a Coffee",
        supportIntroLaterButton: "Nie teraz",
        supportIntroDoneButton: "Gotowe",
        discordIntroTitle: "Społeczność Vorssaint na Discordzie dopiero się rozwija",
        discordIntroMessage: "Społeczność Vorssaint jest nowa i dopiero powstaje. Dołącz wcześnie, poznaj innych użytkowników i pomóż tworzyć przyjazne miejsce wokół aplikacji.",
        discordIntroJoinButton: "Dołącz do społeczności Discord",
        communityIntroTitle: "Zobacz zanim zobaczą inni",
        communityIntroMessage: "Osoby, które obserwują mnie na X, widzą część zmian wcześniej. Pokazuję tam zapowiedzi tego, co nadchodzi, i jak to działa.",
        communityIntroFollowButton: "Obserwuj @vorssaint na X",
        homebrewOfficialIntroTitle: "Vorssaint w oficjalnym katalogu Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint można teraz instalować bezpośrednio z oficjalnego katalogu Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nowa instalacja",
        homebrewOfficialIntroMigrationTitle: "Używasz starego tapa?",
        homebrewOfficialIntroMigrationMessage: "Usuń tap raz. Aplikacja i ustawienia pozostaną na miejscu.",
        homebrewOfficialIntroCopyButton: "Kopiuj polecenie",
        updateShowcaseTitle: "Co nowego w 3.1.4",
        updateShowcaseMessage: "Zobacz najważniejsze ulepszenia w tej aktualizacji.",
        updateShowcaseUnavailable: "Film nie może się teraz załadować. Możesz mimo to kontynuować.",
        updateShowcaseRestart: "Uruchom ponownie",
        showMenuBarIcon: "Pokaż ikonę na pasku menu",
        menuBarIconStillHiddenTitle: "Ikona nadal jest ukryta",
        menuBarIconStillHiddenBody: "Ikona została odbudowana, ale macOS nie przydzielił jej widocznego miejsca. Pasek menu może być pełny: usuń część ikon lub zamknij aplikacje z długimi menu i spróbuj ponownie.",
        menuBarIconManagerHintFormat: "%@ jest otwarty i może utrzymywać ikonę w ukrytej sekcji. Poszukaj tam Vorssaint albo ustaw %@ tak, aby zawsze pokazywał Vorssaint.",
        menuBarIconDisallowedBody: "macOS nie pozwala Vorssaint wyświetlać się na pasku menu. Otwórz Ustawienia systemowe → Pasek menu, znajdź Vorssaint na liście aplikacji i włącz „Pozwól na pasku menu”. Ikona pojawi się po włączeniu przełącznika.",
        shortcutRecording: "Naciśnij nowy skrót",
        shortcutReset: "Resetuj",
        shortcutNone: "Brak",
        shortcutClear: "Usuń skrót",
        shortcutInvalid: "Użyj co najmniej klawisza Control, Option lub Command wraz z klawiszem.",
        shortcutPressKeys: "Naciśnij klawisze",
        shortcutEscapeHint: "Escape anuluje.",
        shortcutDeleteHint: "Delete usuwa.",
        shortcutNotCaptured: "Nic nie zostało przechwycone. macOS lub inna aplikacja używa już tej kombinacji. Spróbuj innej.",
        shortcutConflictFormat: "Ten skrót jest już używany przez %@",
        shortcutTakeOverOffer: "macOS używa %@ do jednego ze swoich skrótów.",
        shortcutTakeOverAction: "Przejmij, gdy działa Vorssaint",
        shortcutTakeOverCaption: "macOS odzyskuje klawisz, gdy Vorssaint nie działa lub ta funkcja jest wyłączona.",
        shortcutTakeOverDismiss: "Nie przejmuj",
        shortcutUnavailable: "macOS odrzucił ten skrót. Wybierz inny.",
        shelfShortcutToggle: "Skrót półki",
        switcherUsageHintFormat: "Przytrzymaj %@, aby nawigować; zwolnij, aby aktywować okno. Shift lub ← cofa; W zamyka okno; Q kończy aplikację; Esc anuluje.",
        musicBlockSection: "Klawisze multimedialne",
        musicBlockTitle: "Zatrzymaj samoczynne otwieranie Muzyki",
        musicBlockCaption: "Blokuje otwieranie aplikacji muzycznej po wykryciu klawisza multimedialnego. Wymaga Dostępności. Polecenia słuchawkowe bez wykrytego klawisza pozostają bez zmian.",
        musicBlockUnavailable: "Ta ochrona jest teraz niedostępna. Wyłącz ją i włącz ponownie.",
        musicBlockReplacementLabel: "Otwórz zamiast tego",
        musicBlockReplacementNone: "Brak",
        musicBlockChooseApp: "Wybierz aplikację…",
        cleanerName: "Oczyszczanie",
        cleanerIntroTitle: "Posprzątaj Maca",
        cleanerIntroCaption: "Skanuje pozostałości po odinstalowanych aplikacjach, pamięci podręczne, logi i Kosz. Wszystko sprawdzasz przed usunięciem, a elementy trafiają do Kosza.",
        cleanerScan: "Skanuj",
        cleanerScanning: "Skanowanie…",
        cleanerCleaning: "Czyszczenie…",
        cleanerCatLeftovers: "Pozostałości po odinstalowanych aplikacjach",
        cleanerCatLoginItems: "Osierocone elementy startowe",
        cleanerCatCaches: "Pamięć podręczna",
        cleanerCatLogs: "Logi",
        cleanerCatDeveloper: "Śmieci deweloperskie",
        cleanerCatTrash: "Kosz",
        cleanerLeftoversNote: "Znaleziono podczas analizy i pozostawiono odznaczone. Sprawdź ścieżkę przed zaznaczeniem.",
        cleanerLoginItemsNote: "Wpis zniknie z Elementów logowania po ponownym uruchomieniu Maca.",
        cleanerTrashNote: "Opróżnienie Kosza jest nieodwracalne.",
        cleanerCatDeviceBackups: "Kopie zapasowe iPhone’a",
        cleanerDeviceBackupsCaption: "Stare kopie iPhone’a i iPada zajmują dużą część pamięci, którą macOS określa jako Inne. Usuwaj tylko te, których już nie potrzebujesz.",
        cleanerNothingFound: "Nic do wyczyszczenia. Twój Mac jest uporządkowany.",
        cleanerClean: "Wyczyść",
        cleanerDoneNote: "Elementy trafiły do Kosza i można je stamtąd odzyskać.",
        cleanerAgain: "Skanuj ponownie",
        cleanerRevealInFinder: "Pokaż w Finderze",
        cleanerPanelCaption: "Pozostałości aplikacji, pamięć podręczna i logi",
        cleanerSafeSection: "Bezpieczne czyszczenie",
        cleanerOptionalSection: "Opcjonalne, wymagają sprawdzenia",
        cleanerCatOtherCaches: "Inne pamięci podręczne",
        cleanerCachesCaption: "Pliki tymczasowe, które aplikacje odtwarzają samodzielnie.",
        cleanerLogsCaption: "Stare logi diagnostyczne.",
        cleanerDeveloperCaption: "Pozostałości po kompilacjach Xcode i symulatorach.",
        cleanerLoginItemsCaption: "Elementy startowe pozostawione przez nieistniejące już aplikacje.",
        cleanerLeftoversCaption: "Pliki pozostawione przez odinstalowane aplikacje.",
        cleanerOtherCachesCaption: "Można bezpiecznie usunąć. Nic się nie zepsuje; aplikacje mogą tylko raz uruchomić się wolniej, a pobrane treści pobiorą się ponownie.",
        cleanerCleanSizeFormat: "Wyczyść %@",
        cleanerScheduleTitle: "Automatyczne czyszczenie",
        cleanerScheduleOff: "Wyłączone",
        cleanerScheduleDaily: "Codziennie",
        cleanerScheduleWeekly: "Co tydzień",
        cleanerScheduleCaption: "Automatycznie czyści tylko bezpieczną część o wybranej porze i przenosi wszystko do Kosza.",
        cleanerScheduleLastFormat: "Ostatnie automatyczne czyszczenie zwolniło %@.",
        cleanerAutoNotificationFormat: "Zwolniono %@ i przeniesiono do Kosza.",
        cleanerScheduleNextFormat: "Następne czyszczenie %@.",
        cleanerScheduleRanFormat: "Ostatnie automatyczne czyszczenie %@.",
        cleanerScheduleNotifyToggle: "Powiadamiaj po zakończeniu",
        cleanerNotifDenied: "Powiadomienia Vorssaint są wyłączone w systemie.",
        cleanerNotifOpenSettings: "Otwórz Ustawienia powiadomień…",
        launchAtLoginNeedsApplications: "Aplikacja działa z miejsca, którego nie można otwierać przy logowaniu. Przenieś Vorssaint do folderu Programy, uruchom stamtąd i włącz tę opcję ponownie.",
        launchAtLoginNeedsApproval: "Element logowania jest zarejestrowany, ale nadal wyłączony w Ustawieniach systemowych. Otwórz Ustawienia systemowe › Ogólne › Elementy logowania i rozszerzenia i włącz Vorssaint w sekcji Otwieraj przy logowaniu.",
        ocrRemoveLineBreaksToggle: "Usuń łamania wierszy",
        ocrRemoveLineBreaksCaption: "Usuwa podziały wierszy, aby skopiowany tekst wklejał się jako jeden akapit.",
        ocrQRToggle: "Odczytuj kody QR",
        ocrQRCaption: "Jeśli obszar zawiera kod QR, jego zawartość zostanie pokazana do skopiowania lub otwarcia.",
        ocrQRCopied: "Kod QR skopiowany",
        qrResultTitle: "Kod QR",
        qrResultCopy: "Kopiuj",
        qrResultOpen: "Otwórz link",
        highlightsTitle: "Nowości w tej aktualizacji",
        highlightsTitleClipboardRedesign: "Przeprojektowany schowek",
        highlightsTitleWindowLayout: "Układ okien",
        highlightsTitleQuitProtection: "Ochrona przed zamykaniem i kończeniem aplikacji",
        highlightsTitleRecorderBlur: "Rozmycie prywatnych danych podczas nagrywania",
        highlightsCaptionDockPreview: "Podgląd Docka działa teraz z włączonym powiększeniem Docka",
        highlightsCaptionScreenshot: "Narzędzie zrzutów ekranu dostało lupę pikselową i odczytywanie kodów QR",
        highlightsCaptionSnippetLibrary: "Przeszukiwane menu fragmentów wpisuje dowolny fragment bezpośrednio w miejscu kursora",
        highlightsCaptionCapturePalette: "Jeden skrót otwiera pływający panel zrzutów, nagrań, tekstu z ekranu i kolorów.",
        highlightsCaptionClipboardRedesign: "Historia schowka otwiera się teraz jako kompaktowa paleta z uporządkowanymi wierszami i podglądem na żądanie do odczytu lub edycji całego elementu.",
        highlightsCaptionWindowLayout: "Pozycjonuj okna za pomocą pierścienia kierunkowego, skrótu i wskaźnika albo przeciągaj je do krawędzi ekranu, aby przyciągać z własnymi odstępami.",
        highlightsCaptionQuitProtection: "Unikaj przypadkowego kończenia aplikacji lub zamykania okien dzięki przytrzymaniu, podwójnemu naciśnięciu albo dodatkowemu modyfikatorowi, konfigurowalnemu dla każdej aplikacji.",
        highlightsCaptionRecorderBlur: "Ukrywaj prywatne dane, hasła i wrażliwe obszary w dowolnym miejscu nagranego filmu przed udostępnieniem lub eksportem.",
        highlightsConfigure: "Skonfiguruj",
        highlightsTry: "Wypróbuj",
        highlightsSeeAll: "Zobacz wszystkie zmiany",
        switcherCurrentSpaceOnly: "Pokaż tylko bieżące biurko",
        switcherCurrentSpaceOnlyCaption: "Pokazuje tylko okna z bieżącego biurka. Wybór okna nigdy nie przenosi na inne biurko.",
        shelfFileMissing: "Plik już nie istnieje",
        previewSizeSmall: "Mały",
        mixerSoundEffectsOutputTitle: "Dźwięki systemowe",
        mixerSoundEffectsOutputTooltip: "Wybierz, gdzie odtwarzać alerty i efekty dźwiękowe",
        monitorOpenActivityMonitor: "Otwórz Monitor aktywności",
        dockClickHide: "Kliknij ikonę Docka, aby ukryć aplikację",
        dockClickHideCaption: "Aktywna aplikacja ukrywa się po kliknięciu jej ikony w Docku. Kliknij ponownie, aby ją przywrócić.",
        monitorMemoryMetricLabel: "Pokazuj pamięć jako",
        memoryMetricUsed: "Użycie pamięci",
        memoryMetricApp: "Pamięć aplikacji",
        keepAwakeRightClickToggle: "Kliknij prawym przyciskiem ikonę paska menu, aby przełączać „Nie usypiaj”",
        keepAwakeRightClickToggleCaption: "Zastępuje menu kontekstowe prawego przycisku.",
        urlCleanerRulesTitle: "Reguły czyszczenia",
        urlCleanerRulesCaption: "Witryna dodaje te parametry do własnych linków udostępniania, aby śledzić źródło linku. Po włączeniu reguły nazwa parametru jest usuwana podczas czyszczenia linku; po wyłączeniu pozostaje. Dodane nazwy można usuwać.",
        urlCleanerRulesCoverageCaption: "Lista obejmuje różne ścieżki udostępniania witryny (stronę WWW, aplikację i pokój na żywo), dlatego jest długa; rzeczywisty link zwykle zawiera tylko od dwóch do czterech z nich.",
        urlCleanerRulesAllSites: "Wszystkie witryny",
        urlCleanerRulesCountSingular: "1 parametr",
        urlCleanerRulesCountPluralFormat: "%d parametrów",
        urlCleanerRulesAddSite: "Dodaj witrynę",
        urlCleanerRulesParameterPlaceholder: "Nazwa parametru",
        urlCleanerRulesMatchCaption: "Wpisz nazwę po lewej stronie znaku =, np. utm_source. Pasująca nazwa usuwa ten parametr z linku i pozostawia resztę bez zmian.",
        urlCleanerRulesAddButton: "Dodaj",
        urlCleanerRulesRemoveButton: "Usuń nazwę",
        urlCleanerRulesRemoveSiteButton: "Wyłącz wszystkie reguły dla tej witryny",
        urlCleanerRemovedFormat: "Usunięto %@",
        switcherSearchPin: "Przypnij wyszukiwanie klawiszem S",
        switcherSearchPinCaption: "S rozpoczyna wyszukiwanie i przypina przełącznik, więc pisanie nie generuje znaków specjalnych, gdy skrót używa ⌥, a wyszukiwanie zaczynające się od Q lub W nie zamyka przypadkowo okna ani nie kończy aplikacji.",
        invertVerticalScroll: "Odwróć przewijanie w pionie",
        invertHorizontalScroll: "Odwróć przewijanie w poziomie",
        scrollHorizontalName: "Przewijaj na boki przytrzymując klawisz",
        scrollHorizontalModifierLabel: "Klawisz modyfikujący",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Przytrzymaj tylko wybrany klawisz modyfikujący, aby przewijać kółkiem myszy w poziomie.",
        switcherShowShortcutHints: "Pokaż podpowiedzi skrótów",
        switcherShowShortcutHintsCaption: "Pokazuje skróty aplikacji i okien pod ikonami.",
        uninstallerHomebrewPackageFormat: "%@ zostanie również usunięty z Homebrew.",
        shelfEdgeToggle: "Otwieraj przy krawędzi ekranu",
        shelfEdgeCaption: "Przeciągnij plik do krawędzi ekranu, aby wysunąć półkę. Upuść albo cofnij, a półka się schowa.",
        focusFollowsMouseName: "Fokus podąża za wskaźnikiem",
        focusFollowsMouseCaption: "Po krótkiej chwili aktywuje okno znajdujące się pod wskaźnikiem i przenosi je na wierzch.",
        focusFollowsMouseDelay: "Opóźnienie najechania",
        switcherMinimizedPlacementLabel: "Zminimalizowane okna i ukryte aplikacje",
        switcherMinimizedPlacementNormal: "Normalna kolejność",
        switcherMinimizedPlacementEnd: "Umieść na końcu",
        switcherMinimizedPlacementHidden: "Ukryj",
        switcherShowFullscreenWindows: "Pokaż okna pełnoekranowe",
        switcherScreenPlacementLabel: "Pokaż na",
        switcherScreenPlacementPointer: "Ekran ze wskaźnikiem",
        switcherScreenPlacementMenuBar: "Ekran z paskiem menu",
        switcherScreenPlacementActiveWindow: "Ekran z aktywnym oknem",
        switcherScreenPlacementCaption: "Ekran, na którym otwiera się przełącznik, gdy podłączonych jest więcej monitorów.",
        switcherCurrentDisplayOnly: "Pokaż tylko bieżący ekran",
        switcherCurrentDisplayOnlyCaption: "Pokazuje tylko okna na ekranie pod wskaźnikiem. Jeśli na tym ekranie nie ma okien, przełącznik się nie otworzy.",
        smoothScrollResponseLabel: "Reakcja",
        smoothScrollCoastLabel: "Bezwładność",
        mouseAccelerationName: "Wyłącz akcelerację myszy",
        mouseAccelerationCaption: "Usuwa akcelerację wskaźnika dla podłączonych myszy. Poprzednie ustawienie wraca po wyłączeniu tej opcji lub zamknięciu Vorssaint.",
        shelfClearOnClose: "Wyczyść po zamknięciu",
        shelfClearOnCloseCaption: "Opróżnia półkę tylko po kliknięciu przycisku zamknięcia. Automatyczne ukrywanie i zwijanie zachowują elementy."
    )
}
